<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Arus Listrik dan Hukum Ohm</name>
   <tag></tag>
   <elementGuidId>8c2b123d-a95a-45ab-838b-4e73b08c276c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/section/article/div/div/div[2]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.chakra-text.css-17cqkbj</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7f5f3dbf-60dc-42f3-8f3d-ba6821ca6e64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-text css-17cqkbj</value>
      <webElementGuid>e9e9fb31-4054-4a5b-8778-81e8b2983662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ruangbelajar/v/arus-listrik-dan-hukum-ohm-subtopi-9mfzn9ui-hr-sma-kelas-12-kurikulum-merdeka</value>
      <webElementGuid>6ba75c16-05cc-4404-bd26-69a0909b8cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Arus Listrik dan Hukum Ohm</value>
      <webElementGuid>dda2ed1b-dd8b-4ec3-8cb0-f7688a9f6f77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;css-1f5whys&quot;]/div[@class=&quot;css-1ubbntx&quot;]/section[@class=&quot;chakra-stack css-evkuat&quot;]/article[@class=&quot;chakra-stack css-1egbou&quot;]/div[@class=&quot;css-ad2za6&quot;]/div[@class=&quot;css-lcuzc0&quot;]/div[@class=&quot;css-11x96np&quot;]/div[@class=&quot;css-1a52s2z&quot;]/a[@class=&quot;chakra-text css-17cqkbj&quot;]</value>
      <webElementGuid>768b1ce4-8457-4e65-a28d-a4b3bb376f3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/section/article/div/div/div[2]/div/a</value>
      <webElementGuid>90d58250-6dbf-47ac-b63a-daf0bda47583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Arus Listrik dan Hukum Ohm')]</value>
      <webElementGuid>baa8fe69-f0ac-4716-9f44-86527bfd1d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Energi Listrik dan Daya Listrik'])[1]/following::a[20]</value>
      <webElementGuid>6cc24ee9-48f5-4ae4-ac6b-f20e1a0084e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tegangan dan Hambatan Dalam pada Baterai'])[1]/following::a[22]</value>
      <webElementGuid>7dfb34a7-76db-46c3-be0d-a3ff64c58def</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rangkaian Hambatan Listrik'])[2]/preceding::a[1]</value>
      <webElementGuid>ba51b3a7-8d5b-458d-afe5-4e63ce77a7d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hukum Kirchoff'])[2]/preceding::a[2]</value>
      <webElementGuid>03e887b9-8458-406b-87db-e5bd06b28cf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/ruangbelajar/v/arus-listrik-dan-hukum-ohm-subtopi-9mfzn9ui-hr-sma-kelas-12-kurikulum-merdeka')])[2]</value>
      <webElementGuid>351a4fc3-6e5f-4e18-a85d-da1bc7791bc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/div/div[2]/div/a</value>
      <webElementGuid>4042e4cd-3029-46c9-b989-4f30986805e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ruangbelajar/v/arus-listrik-dan-hukum-ohm-subtopi-9mfzn9ui-hr-sma-kelas-12-kurikulum-merdeka' and (text() = 'Arus Listrik dan Hukum Ohm' or . = 'Arus Listrik dan Hukum Ohm')]</value>
      <webElementGuid>0419ae92-f073-497b-bd65-1e2a59534110</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
