<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Email yang dimasukkan tidak benar</name>
   <tag></tag>
   <elementGuidId>379cf0fc-f135-46e0-9710-5ba6217b451d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-1-feedback</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='field-1-feedback']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>07865d29-78f2-40e6-8d80-35eb2112ced4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-1-feedback</value>
      <webElementGuid>be505f92-924b-4a04-a694-d377fd8b220a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>6ddfec4c-b2fc-48b8-bc3c-b9e3b57f8484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-form__error-message css-uv56vk</value>
      <webElementGuid>d2553043-5b8c-4b14-93a4-ca90338bc70a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email yang dimasukkan tidak benar</value>
      <webElementGuid>d452b68f-692b-4347-b40a-d3c1221aa73c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-1-feedback&quot;)</value>
      <webElementGuid>eda12ae6-c924-4e91-8012-51b97b23aa47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='field-1-feedback']</value>
      <webElementGuid>4a745160-b7e0-4a1e-b4ca-1c17fa69c0df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[2]/div[2]/div/div/div/form/div/div[2]</value>
      <webElementGuid>4080099c-815f-40b3-b5be-0b633e2dcfab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facebook'])[1]/following::div[4]</value>
      <webElementGuid>ad056799-80f6-445b-9073-e0e5dcd12d2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lanjutkan'])[1]/preceding::div[1]</value>
      <webElementGuid>bc0243ba-1aaa-4282-a16c-74fc6b61ff44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bantuan'])[1]/preceding::div[2]</value>
      <webElementGuid>b3dbfb26-15d3-4d27-a41b-09ab810ed43f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Email yang dimasukkan tidak benar']/parent::*</value>
      <webElementGuid>f39563dc-9d24-4dac-8404-1ed7ff0449c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]</value>
      <webElementGuid>6b7e2839-cdfd-4e95-a4dc-2a2232877c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'field-1-feedback' and (text() = 'Email yang dimasukkan tidak benar' or . = 'Email yang dimasukkan tidak benar')]</value>
      <webElementGuid>028fab41-866a-4a89-9eb0-ed101353e8f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
