<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Masuk</name>
   <tag></tag>
   <elementGuidId>b940de9c-2011-496c-8bab-4889351ee72a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.link-button.button-transparent > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hs_cos_wrapper_module_168006348270657']/div/div/div/div[3]/div[3]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c86aa326-75fe-4cf2-941a-16538fe38a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>5e79381f-cb6c-4b5c-95bb-8359c6e7e031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://lms.ruangkerja.id/</value>
      <webElementGuid>55a889fa-c538-4732-a8ed-71c7167d1113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>5556f9cc-187d-4fe5-9ae3-4041841aaab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hs_cos_wrapper_module_168006348270657&quot;)/div[@class=&quot;navbar-ba-2022&quot;]/div[@class=&quot;page-center&quot;]/div[@class=&quot;container-navbar-ba&quot;]/div[@class=&quot;navigation__right&quot;]/div[@class=&quot;cta-header&quot;]/div[@class=&quot;link-button button-transparent&quot;]/a[1]</value>
      <webElementGuid>d12ba010-6e54-486c-b23f-4a85eea333c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hs_cos_wrapper_module_168006348270657']/div/div/div/div[3]/div[3]/div/a</value>
      <webElementGuid>e3f57a49-719e-4b5e-b8ca-be3ba921f71e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Masuk')]</value>
      <webElementGuid>ce255c4a-04dd-46bd-87f6-d3a8e2728f04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/following::a[1]</value>
      <webElementGuid>888d2d8d-8cd6-4784-94b6-4bc29c072ee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bahasa Indonesia'])[1]/following::a[2]</value>
      <webElementGuid>470c9cd0-b8b4-4785-baac-e98eddca3934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dapatkan Demo'])[1]/preceding::a[1]</value>
      <webElementGuid>f4e13b92-5409-43f6-9fb5-355ce258435d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Platform edukasional untuk pelatihan online dan offline perusahaan'])[1]/preceding::a[2]</value>
      <webElementGuid>4320906e-3cc9-4c26-8dd2-d0b998c0f30b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Masuk']/parent::*</value>
      <webElementGuid>21bb2625-5a84-4616-8ea7-079c8d69b9e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://lms.ruangkerja.id/')]</value>
      <webElementGuid>db754b95-3f18-4aa5-8d7d-1cea83102a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/a</value>
      <webElementGuid>697a43f5-53a3-40ef-b24c-9c33b7c2d248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://lms.ruangkerja.id/' and (text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>a8d43503-1b96-49f2-8442-8e9bdab87862</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
