<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Program</name>
   <tag></tag>
   <elementGuidId>f4000385-81ac-4f83-b9f5-bf3e305dd6cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#program > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='program']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c4a1abc8-495d-42a1-8dfd-ed101fc690db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking-event-type</name>
      <type>Main</type>
      <value>landing_page__core__item_click</value>
      <webElementGuid>312a638d-f7de-484d-b917-22d90b6d5c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking-context</name>
      <type>Main</type>
      <value>{&quot;product_name&quot;: &quot;ruangguru&quot;,&quot;cta_action&quot;: &quot;redirection&quot;,&quot;cta_action_detail&quot;: &quot;https://www.ruangguru.com/program&quot;,&quot;item_type&quot;: &quot;link&quot;,&quot;item_name&quot;: &quot;Program&quot;,&quot;item_category&quot;: &quot;cta&quot;,&quot;item_position&quot;: 2,&quot;item_serial&quot;: null,&quot;section_type&quot;: &quot;navbar&quot;,&quot;section_position&quot;: &quot;header&quot;,&quot;section_name&quot;: &quot;header_navbar&quot;}</value>
      <webElementGuid>cb06abb2-6633-4509-b273-48e06e4df6cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.ruangguru.com/program</value>
      <webElementGuid>74394d7a-befe-4598-959d-acc458ffa8b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Program</value>
      <webElementGuid>c503d2f4-5016-4fde-9eda-450ddabdaf2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;program&quot;)/a[1]</value>
      <webElementGuid>3d404eab-7c18-4233-8327-9c82f671cc3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='program']/a</value>
      <webElementGuid>89194599-d5ec-4a40-822d-0680c1b2d784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Program')]</value>
      <webElementGuid>b6c2c663-5179-4494-ad67-3528090bc914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promo'])[1]/preceding::a[1]</value>
      <webElementGuid>dd483144-ce87-4628-a8af-09fabea3dcd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event'])[1]/preceding::a[2]</value>
      <webElementGuid>3debbc95-6610-41c0-aca1-35f5089120f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Program']/parent::*</value>
      <webElementGuid>4af23d7f-5549-40fc-8b23-2c316b239e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.ruangguru.com/program')]</value>
      <webElementGuid>b2a13bad-d2fe-4a99-80f7-5b86d7af77c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>6d9fa67f-9f3a-4cf7-9b62-766f54f902f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.ruangguru.com/program' and (text() = 'Program' or . = 'Program')]</value>
      <webElementGuid>fbb8277a-772e-4cb7-ba10-3381f5840b49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
