<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Layanan</name>
   <tag></tag>
   <elementGuidId>243b9416-e537-47b8-b073-748b878d6b29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#services > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='services']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f8476eca-bc5c-4bc1-be27-002d682aaf03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>79ccad2f-74e2-4d5d-8d58-66893a7dc3c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Layanan</value>
      <webElementGuid>5d9674ea-8b07-48a7-bec0-54441bbb8bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;services&quot;)/a[1]</value>
      <webElementGuid>a9b74de7-35b7-4e20-b86c-3ae5a48c7ce2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='services']/a</value>
      <webElementGuid>ab68ea38-5a81-4955-afab-5426db1920fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Layanan')]</value>
      <webElementGuid>6061370a-d21e-48a1-97b4-9e3da8b57fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Testimoni'])[1]/following::a[1]</value>
      <webElementGuid>e2550aa9-44af-4db9-9042-5e3e813cad76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beasiswa'])[1]/following::a[2]</value>
      <webElementGuid>55c3dae9-1f07-43e5-a93c-23252c018d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cara Perpanjang Paket'])[1]/preceding::a[1]</value>
      <webElementGuid>4ba3cfc3-e0ac-400f-b681-b47f0afc1746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cara Bayar'])[1]/preceding::a[2]</value>
      <webElementGuid>7f8f5b4a-a6d1-492e-b5e2-a3555295f943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Layanan']/parent::*</value>
      <webElementGuid>9028d3a8-de3d-420e-a9c0-7f50070561d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>2f68c51b-aa8f-482a-a773-d688538d9466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/a</value>
      <webElementGuid>038de5b8-1bee-44c0-82ca-604092c2f5c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Layanan' or . = 'Layanan')]</value>
      <webElementGuid>4afbf6c6-052e-4151-97c4-736491b439ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
