<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pilih</name>
   <tag></tag>
   <elementGuidId>643dfb3d-10ca-4a2b-b72c-2bb7d5d87a45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kontenSprinter > div.card-content-program > div.card-bottom-program > a.card-bottom-cta</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kontenSprinter']/div/div[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ea7359bb-5a10-4f7d-9d0c-31d64a84430d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-bottom-cta</value>
      <webElementGuid>04c661ef-6629-4155-822c-2b3448d8e6b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://bayar.ruangguru.com/npf/package/PKG-H8VM1JTV?referralCookiesId=8d611a04-79fc-460a-a81a-8c35868dcd1f&amp;_ga=2.148084919.1099942511.1682430128-1288278588.1682430128</value>
      <webElementGuid>5c81ae87-0363-4956-83f9-7a7192ec2c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>38ea8f53-d0d3-4862-b64f-4cc86ed16748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3fd051c4-3dbb-42bb-9275-3ef98a036872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih</value>
      <webElementGuid>fd0c0879-481e-44a7-a440-68f1ea81fd25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kontenSprinter&quot;)/div[@class=&quot;card-content-program&quot;]/div[@class=&quot;card-bottom-program&quot;]/a[@class=&quot;card-bottom-cta&quot;]</value>
      <webElementGuid>ee60e368-995a-42cc-abc7-a2aaaa185b9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kontenSprinter']/div/div[3]/a</value>
      <webElementGuid>233bfa3a-7f0c-49d1-a401-a564b7452f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Pilih')])[22]</value>
      <webElementGuid>c134a542-40ba-4080-a6db-b603fe0bb7c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Selengkapnya'])[4]/following::a[1]</value>
      <webElementGuid>74bcae65-703e-4001-82b5-6b9f6bddf445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belajar lebih seru dengan fitur Star Champs'])[1]/following::a[2]</value>
      <webElementGuid>ed91cc2f-0c6a-42a6-a79e-2f0256021557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih'])[23]/preceding::a[1]</value>
      <webElementGuid>ec57bd45-23cf-4cca-aa32-47f7f20073dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih'])[24]/preceding::a[2]</value>
      <webElementGuid>8ddc2d7e-b170-46fb-ba9f-f3af2b876986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://bayar.ruangguru.com/npf/package/PKG-H8VM1JTV?referralCookiesId=8d611a04-79fc-460a-a81a-8c35868dcd1f&amp;_ga=2.148084919.1099942511.1682430128-1288278588.1682430128')]</value>
      <webElementGuid>50c8ecfe-b5f3-40ff-846c-409d2ad1f7a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/div[3]/a</value>
      <webElementGuid>35b5537f-2252-4f78-9160-a23c7ed27af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://bayar.ruangguru.com/npf/package/PKG-H8VM1JTV?referralCookiesId=8d611a04-79fc-460a-a81a-8c35868dcd1f&amp;_ga=2.148084919.1099942511.1682430128-1288278588.1682430128' and (text() = 'Pilih' or . = 'Pilih')]</value>
      <webElementGuid>a0ea31f9-d056-4db3-a93f-3cd3c8a43e12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
