<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_reward_form_submissionsubmissio_b84820</name>
   <tag></tag>
   <elementGuidId>273f1395-3cb7-4ec0-bad1-af3086cd652e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reward_form_submission_submission_data_email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reward_form_submission_submission_data_email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dcc7f78d-3044-47ad-954d-64d812ec30aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>132e6ae8-8681-48b0-b9d8-5835705eac73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>9eeb7899-ea4d-4ad7-9c47-b8523ee36212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan email</value>
      <webElementGuid>4f0f71f4-2134-47d7-b065-de3e2d6fe209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>01e3ba68-5dae-47bc-8951-8a7f7695bfba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reward_form_submission[submission_data][email]</value>
      <webElementGuid>f3748e2e-15fb-4ef2-b8d4-6ff2bfaa0b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reward_form_submission_submission_data_email</value>
      <webElementGuid>c9413c61-7d83-44ae-b4bb-182aac238c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reward_form_submission_submission_data_email&quot;)</value>
      <webElementGuid>c14ace98-ccc5-4f7f-b6ea-4ba1a4f598e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reward_form_submission_submission_data_email']</value>
      <webElementGuid>49f4b58d-2351-490e-883a-59a7cbdb0ef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='wizard-p-0']/div[16]/input</value>
      <webElementGuid>af614b12-b8aa-458a-912c-5fd66457a14a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/input</value>
      <webElementGuid>dbc29fee-f913-45e9-b397-4fb7f1456deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Masukan email' and @type = 'email' and @name = 'reward_form_submission[submission_data][email]' and @id = 'reward_form_submission_submission_data_email']</value>
      <webElementGuid>386551b7-143a-4616-9b9f-69ffab8b64b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
