<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Offline hanya tersedia untuk JABODETA_1c5a3e</name>
   <tag></tag>
   <elementGuidId>86d10f3e-9e91-49bd-8d99-48275971a540</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reward_form_submission_submission_data_pilihan_paket_akademik_paket_fokus_-_16_sesi_online_-_rp160_000sesi_-_total__rp2_560_000']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reward_form_submission_submission_data_pilihan_paket_akademik_paket_fokus_-_16_sesi_online_-_rp160_000sesi_-_total__rp2_560_000</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c61a0baa-f5f7-4005-bd10-ec4e3e7240a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input input-radio</value>
      <webElementGuid>1d13ca68-2712-4cbc-956d-c4cc1041af47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dependent-field-visibility</name>
      <type>Main</type>
      <value>visible</value>
      <webElementGuid>c57e4b13-42b3-42cc-92b0-4c4e63603e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dependent-field-name</name>
      <type>Main</type>
      <value>reward_form_submission[submission_data][pilihan_program]</value>
      <webElementGuid>75106a6d-15fa-45b6-aa1b-b843e5e79bbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dependent-field-value</name>
      <type>Main</type>
      <value>paket_akademik</value>
      <webElementGuid>3ca796b7-a9b8-4ef0-bd74-7489b597e90b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Pilihan Paket</value>
      <webElementGuid>ac74e957-0be2-4d15-b8db-d9d063fa77e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label-type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d290e3db-f1a9-415b-b711-8243467bf219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>da16810a-be19-478f-b8ba-e82d4e725522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Paket Fokus - (16 Sesi Online) - Rp160.000/sesi - Total = Rp2.560.000</value>
      <webElementGuid>bd83644d-eba8-4a13-9b41-64868301c152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reward_form_submission[submission_data][pilihan_paket_akademik]</value>
      <webElementGuid>b307f959-7c6e-47cd-a8b0-87684d43d707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reward_form_submission_submission_data_pilihan_paket_akademik_paket_fokus_-_16_sesi_online_-_rp160_000sesi_-_total__rp2_560_000</value>
      <webElementGuid>c31fb498-9e6d-488f-86fb-218db93f226a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>bc7be938-a19f-4bce-b208-61d6d2280034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reward_form_submission_submission_data_pilihan_paket_akademik_paket_fokus_-_16_sesi_online_-_rp160_000sesi_-_total__rp2_560_000&quot;)</value>
      <webElementGuid>3ad38f67-103b-45d0-b447-0e08ac0a820a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reward_form_submission_submission_data_pilihan_paket_akademik_paket_fokus_-_16_sesi_online_-_rp160_000sesi_-_total__rp2_560_000']</value>
      <webElementGuid>72a79931-acf4-4abd-8884-08ca4d4eeba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='option-pilihan_paket_akademik-0']/input</value>
      <webElementGuid>00333ac3-4e3f-494a-a602-7cad2889bfb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>1012bb45-d89f-48d2-9fec-2133274b19b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'reward_form_submission[submission_data][pilihan_paket_akademik]' and @id = 'reward_form_submission_submission_data_pilihan_paket_akademik_paket_fokus_-_16_sesi_online_-_rp160_000sesi_-_total__rp2_560_000']</value>
      <webElementGuid>e9e54cc7-d74e-4141-bce1-8633574ae0b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
