<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Asik dan Seru_reward_form_submissions_e29ccd</name>
   <tag></tag>
   <elementGuidId>c43551e0-4815-44ea-aedc-9e0dcacf9376</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reward_form_submission_submission_data_tipe_pengajar_pelan_tapi_pasti']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reward_form_submission_submission_data_tipe_pengajar_pelan_tapi_pasti</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb9d42d5-b149-4252-a35d-55b5d6d4962a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input input-radio </value>
      <webElementGuid>5f65b833-c088-40e1-897b-f3188601fcbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>f55966f6-b661-435b-ad77-50dd6e607ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Tipe pengajar</value>
      <webElementGuid>0f008a9f-1fbd-48df-9c6e-c5fb82cfaad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label-type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>cdec246b-2771-4242-98a3-53958c6168aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>3c5e9588-ab72-4b7e-8eb8-0443f1b22939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Pelan tapi Pasti</value>
      <webElementGuid>450ac1a1-af33-4903-a73c-8c1f6d1ccbbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reward_form_submission[submission_data][tipe_pengajar]</value>
      <webElementGuid>7932fc4c-3580-4711-81d0-d33126f9cb13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reward_form_submission_submission_data_tipe_pengajar_pelan_tapi_pasti</value>
      <webElementGuid>a9dd2d87-48fc-4f8d-bbbc-d2f0f571667d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reward_form_submission_submission_data_tipe_pengajar_pelan_tapi_pasti&quot;)</value>
      <webElementGuid>d3eeedf5-816d-4fbb-9449-96600be98dcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reward_form_submission_submission_data_tipe_pengajar_pelan_tapi_pasti']</value>
      <webElementGuid>999b35a3-1554-438d-a9f4-7fade9a02a74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='option-tipe_pengajar-2']/input</value>
      <webElementGuid>a83f3dd5-a6f4-4e6c-9c05-ab888de20d2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div[3]/input</value>
      <webElementGuid>941d00c3-ab71-466c-92cd-be21cf4486bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'reward_form_submission[submission_data][tipe_pengajar]' and @id = 'reward_form_submission_submission_data_tipe_pengajar_pelan_tapi_pasti']</value>
      <webElementGuid>ab5ffa42-7bfe-449c-b35d-7671cacf8f8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
