<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pilihan hari_reward_form_submissionsu_e3317f</name>
   <tag></tag>
   <elementGuidId>6d53a376-046e-4ca2-88c7-60b5f5115d90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>A</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;reward_form_submission[submission_data][pilihan_hari][]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dbd89055-f8ed-49ee-b191-28d9f2eb4865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input </value>
      <webElementGuid>3cf24876-5c71-4442-98b3-9bbf381975a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>fc8490a2-2cc6-442d-843f-8ba52c250a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Senin</value>
      <webElementGuid>fb006afa-235b-4b76-8a9f-7b834b4a4c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reward_form_submission[submission_data][pilihan_hari][]</value>
      <webElementGuid>07e9ed00-2097-44c4-a6cd-f136118df163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wizard-p-0&quot;)/div[@class=&quot;form-group form-group-pilihan_hari checkbox-group is-required&quot;]/div[@class=&quot;form-check&quot;]/input[@class=&quot;form-check-input&quot;]</value>
      <webElementGuid>5354eaae-d03c-414d-ba81-8865b2822098</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='reward_form_submission[submission_data][pilihan_hari][]']</value>
      <webElementGuid>aeadae16-7f26-4617-9c07-7051458dae4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='wizard-p-0']/div[9]/div/input</value>
      <webElementGuid>2f2e8d4f-86cf-43f4-b2b3-817c824dcd81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/input</value>
      <webElementGuid>ed5a3d75-b5db-47eb-a1c0-2f911f340f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'reward_form_submission[submission_data][pilihan_hari][]']</value>
      <webElementGuid>d83c2fdd-2aa3-4287-be01-84dad8ebad41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
