<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama lengkap_reward_form_submissionsu_ad91f6</name>
   <tag></tag>
   <elementGuidId>a90857c4-317a-4b2c-bdd4-5db968f40731</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reward_form_submission_submission_data_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reward_form_submission_submission_data_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1eb5905f-4ef9-4028-a9cc-e64a941a2aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>0ab30ada-01b4-4acf-b3ec-777148d216a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>5cfee4d5-3e77-4947-88e7-b380cf9c9147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Isi nama lengkapmu di sini</value>
      <webElementGuid>7089db8b-482a-4ba6-9dfe-6f1eb48d5115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c5df1c0b-1753-482b-a7fc-9469db312f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reward_form_submission[submission_data][name]</value>
      <webElementGuid>b00128c7-3d8a-450e-9bf8-f69fa4aa3242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reward_form_submission_submission_data_name</value>
      <webElementGuid>6705a4ff-7c78-4c67-b193-9a8167f44599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reward_form_submission_submission_data_name&quot;)</value>
      <webElementGuid>f7ad9c6b-be37-4cfa-96f4-a730213aa2fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reward_form_submission_submission_data_name']</value>
      <webElementGuid>0c1f11b8-765a-45c1-8618-baa7791dc182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='wizard-p-0']/div[14]/input</value>
      <webElementGuid>c4f54964-c53b-4fe6-accd-60495ef099d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/input</value>
      <webElementGuid>382556c5-9b25-448d-8bc3-f5c6062ec229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Isi nama lengkapmu di sini' and @type = 'text' and @name = 'reward_form_submission[submission_data][name]' and @id = 'reward_form_submission_submission_data_name']</value>
      <webElementGuid>1a9480a7-2b53-44cd-a8c9-061d6c9c2c7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
