<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pilihlah estimasi jam belajar yang di_2a145c</name>
   <tag></tag>
   <elementGuidId>c33b8170-d85d-4cf7-ae27-84aae324c1e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='reward_form_submission[submission_data][pilihan_waktu][]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;reward_form_submission[submission_data][pilihan_waktu][]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ac88248-f53d-4ac1-90f2-957070f50942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input </value>
      <webElementGuid>be02de69-8221-4c24-8e27-6efdb64cd029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>fe973cb0-cfec-45d5-a5f2-9925ff7ff83e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>09.00 s.d. 12.00 WIB</value>
      <webElementGuid>22570ec0-2e34-4014-b4b8-e2e49f1e1ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reward_form_submission[submission_data][pilihan_waktu][]</value>
      <webElementGuid>50a36896-f8c0-474e-b735-8dff2e4fe470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wizard-p-0&quot;)/div[@class=&quot;form-group form-group-pilihan_waktu checkbox-group is-required&quot;]/div[@class=&quot;form-check&quot;]/input[@class=&quot;form-check-input&quot;]</value>
      <webElementGuid>c4ae9c98-0a3e-49fd-ad51-a928f77fa4e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='reward_form_submission[submission_data][pilihan_waktu][]']</value>
      <webElementGuid>fbc5365d-5d8c-4055-8eee-f04aa1fc51ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='wizard-p-0']/div[10]/div/input</value>
      <webElementGuid>f5e58905-bae4-4670-8c32-20fd6be05f47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/input</value>
      <webElementGuid>ef513869-489b-4a17-9439-7d07a5e2cc14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'reward_form_submission[submission_data][pilihan_waktu][]']</value>
      <webElementGuid>99a7cef0-9dc4-4aea-8c74-2a4c79590a82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
