<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pilihan Paket_reward_form_submissions_fcc16d</name>
   <tag></tag>
   <elementGuidId>e34949f6-cfd4-4a96-9b08-7c495ed130c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reward_form_submission_submission_data_pilihan_program_paket_akademik']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reward_form_submission_submission_data_pilihan_program_paket_akademik</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bcd32e48-cfff-475f-9d96-cb6514cca446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input input-radio </value>
      <webElementGuid>5f6bd11e-9be1-4919-9bc2-d34e5f008d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>402676c3-2e47-4248-9e56-6057fd5c9132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Pilihan Paket</value>
      <webElementGuid>71c13ae7-c24e-40e6-be48-c07eeac0696c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label-type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>46141042-5826-4537-89f7-b48f1cc7070e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>21a53e9a-1d52-4ff2-ae5a-6d4250f8d83e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>paket_akademik</value>
      <webElementGuid>ceac852b-5fb3-4428-806a-fbe8771ed324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reward_form_submission[submission_data][pilihan_program]</value>
      <webElementGuid>f1cef873-c994-4f11-87b1-709590f079f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reward_form_submission_submission_data_pilihan_program_paket_akademik</value>
      <webElementGuid>459a6cb5-beee-4e97-bcf4-5b509e29c2ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reward_form_submission_submission_data_pilihan_program_paket_akademik&quot;)</value>
      <webElementGuid>6ed7694b-51d1-4a36-9c72-e39eae345fde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reward_form_submission_submission_data_pilihan_program_paket_akademik']</value>
      <webElementGuid>53d843e1-4954-48ad-bfd4-601196eb29dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='option-pilihan_program-0']/input</value>
      <webElementGuid>73ea0d71-cdad-4df7-aac6-c3044cb74ba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>d47428d6-1182-43db-80ff-be29fada56d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'reward_form_submission[submission_data][pilihan_program]' and @id = 'reward_form_submission_submission_data_pilihan_program_paket_akademik']</value>
      <webElementGuid>c3c41d84-f40e-440b-b9af-e8231115ad9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
