<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Senin</name>
   <tag></tag>
   <elementGuidId>72350baf-6182-4e23-acd4-0957673f0851</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='wizard-p-0']/div[9]/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>3805344f-641f-476d-b7d1-7b2d631d17bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>reward_form_submission_submission_data_pilihan_hari</value>
      <webElementGuid>516078da-907b-42e5-b612-b59ea4872f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-label text-dark </value>
      <webElementGuid>96d547ae-d6c8-4bdf-af88-390b20edbc01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label-type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>bfd34a1d-c642-49ce-a0a8-e49b2bcd83ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          Senin
        </value>
      <webElementGuid>cd63f3dc-a8b4-412b-9ec1-b285d1dadd0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wizard-p-0&quot;)/div[@class=&quot;form-group form-group-pilihan_hari checkbox-group is-required&quot;]/div[@class=&quot;form-check&quot;]/label[@class=&quot;form-check-label text-dark&quot;]</value>
      <webElementGuid>4c99e9f0-f921-4571-bf5e-be527c0f89e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='wizard-p-0']/div[9]/div/label</value>
      <webElementGuid>e39f9904-c8a3-41e3-9aa7-cfe9b1a2fcca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilihan hari'])[1]/following::label[1]</value>
      <webElementGuid>b3fa029b-2dba-42c9-b47b-ce4ecde98a39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Jenjang'])[1]/following::label[2]</value>
      <webElementGuid>0716b39b-37b7-41d1-bce9-df2de93abfe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selasa'])[1]/preceding::label[1]</value>
      <webElementGuid>6a7ada35-ca51-499d-823c-aae0e2650567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rabu'])[1]/preceding::label[2]</value>
      <webElementGuid>77ffc864-716d-40ba-9231-2dc56ebb3d7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Senin']/parent::*</value>
      <webElementGuid>41f2d6c9-70ec-4964-bb41-efa40258ce47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/label</value>
      <webElementGuid>5ab67f65-8d84-4aed-9bad-f7a223889093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '
          Senin
        ' or . = '
          Senin
        ')]</value>
      <webElementGuid>5bae90f8-d3f3-4728-bb96-e8183d5ca656</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
