<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Rabu</name>
   <tag></tag>
   <elementGuidId>715d993a-92ec-4766-a6eb-fd6785c3b8f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='wizard-p-0']/div[9]/div[3]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>7f4d5625-d74d-4078-abdc-4168deb2f3b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>reward_form_submission_submission_data_pilihan_hari</value>
      <webElementGuid>59aa36ae-d2de-40c1-891e-1981a380d4fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-label text-dark </value>
      <webElementGuid>2a5cce50-8fe3-4aca-9ceb-42d899993dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label-type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1f4b3d12-3efd-469c-86dd-b62485df4c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          Rabu
        </value>
      <webElementGuid>2dfbcd38-14c6-4c95-99d5-2801cf68260d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wizard-p-0&quot;)/div[@class=&quot;form-group form-group-pilihan_hari checkbox-group is-required&quot;]/div[@class=&quot;form-check&quot;]/label[@class=&quot;form-check-label text-dark&quot;]</value>
      <webElementGuid>977f6737-dc33-48a2-981f-544be9d17c06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='wizard-p-0']/div[9]/div[3]/label</value>
      <webElementGuid>272a6108-2d68-4b3a-900f-f01ed015ab31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selasa'])[1]/following::label[1]</value>
      <webElementGuid>6de7f286-06f6-436c-b889-4202210a2d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Senin'])[1]/following::label[2]</value>
      <webElementGuid>cf7cb82d-8228-4281-8793-2dc139169148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kamis'])[1]/preceding::label[1]</value>
      <webElementGuid>e75d322e-8d85-40b2-9f1e-6c4ff2001db8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Jum', &quot;'&quot;, 'at')])[1]/preceding::label[2]</value>
      <webElementGuid>ab059674-4a00-4a5a-b1cc-438b7f3cc2a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rabu']/parent::*</value>
      <webElementGuid>4577882b-af90-43ac-abc3-022f17b038bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[3]/label</value>
      <webElementGuid>4ecea9ef-04ef-4459-bd2d-f373ce84b7d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '
          Rabu
        ' or . = '
          Rabu
        ')]</value>
      <webElementGuid>9c6d0142-ff53-43b6-b4b1-2f7bfdc76311</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
