<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pilih Daftar sebagai_1</name>
   <tag></tag>
   <elementGuidId>9d07c7c0-d1e8-4383-896f-bd1769d22345</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-reward_form_submission_submission_data_role_rgprivat-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-reward_form_submission_submission_data_role_rgprivat-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7814a8eb-f8c6-4b93-8c9c-8a9489323714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>3c39f979-5e69-4382-a55b-13db9f5cfd16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-reward_form_submission_submission_data_role_rgprivat-container</value>
      <webElementGuid>e53f26de-6e98-43bf-8734-94bc0f9a932d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>ad3d0f8c-86bf-4bf9-a2e4-b454b0291d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f4e597a3-75b0-4af7-9c4e-ec78f5ccf99e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Pilih Daftar sebagai</value>
      <webElementGuid>af4bba1e-ba56-46e1-9502-d05787e4dacd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Daftar sebagai</value>
      <webElementGuid>9602ac55-7654-4540-9b06-2e0a428866a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-reward_form_submission_submission_data_role_rgprivat-container&quot;)</value>
      <webElementGuid>5f711e0e-2c7f-476c-bead-d64faed315f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-reward_form_submission_submission_data_role_rgprivat-container']</value>
      <webElementGuid>ee5e306a-1845-4c57-8fd0-76603a577bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='wizard-p-0']/div[13]/span/span/span/span</value>
      <webElementGuid>d4fdf699-bcbc-4472-84a2-8ee402a44977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar sebagai'])[1]/following::span[4]</value>
      <webElementGuid>ac500396-091d-4ff3-be6e-47938c803e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe pengajar lainnya'])[1]/following::span[4]</value>
      <webElementGuid>e25b0deb-0648-4c61-8e5b-22cae622e25f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Kontak'])[1]/preceding::span[3]</value>
      <webElementGuid>a34422c4-7850-480a-b3bd-0fd4bd33d821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama lengkap'])[1]/preceding::span[3]</value>
      <webElementGuid>fb0842c0-a03c-4704-93f4-0d3c9911f804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/span/span/span/span</value>
      <webElementGuid>46f67f7f-9782-40b1-994a-53346fa9fcca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-reward_form_submission_submission_data_role_rgprivat-container' and @title = 'Pilih Daftar sebagai' and (text() = 'Pilih Daftar sebagai' or . = 'Pilih Daftar sebagai')]</value>
      <webElementGuid>5e0372c1-570a-4d1a-b56f-1b1eb1fb5145</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
