<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pilih Jenjang_1</name>
   <tag></tag>
   <elementGuidId>38a263e4-339c-4a8d-a115-501fc3544428</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-reward_form_submission_submission_data_les_jenjang-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-reward_form_submission_submission_data_les_jenjang-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e3c6937b-0f31-4653-ab21-132d1e451de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>65a1dda3-90bb-419e-8c7a-cda32286513d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-reward_form_submission_submission_data_les_jenjang-container</value>
      <webElementGuid>1494b45b-f7a7-4c74-b845-105a4be254e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>2471344e-6a54-4e39-9dd7-26fd8ef9c301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0d6da9e5-bcb6-4d19-9ead-ae897241849d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Pilih Jenjang</value>
      <webElementGuid>290429e5-23b9-491c-b6b2-66a9955097b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Jenjang</value>
      <webElementGuid>3ded67a5-9029-44b5-9dd1-23576e387068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-reward_form_submission_submission_data_les_jenjang-container&quot;)</value>
      <webElementGuid>cf6b5ea2-0ec8-4fed-bd56-450eb19d8d8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-reward_form_submission_submission_data_les_jenjang-container']</value>
      <webElementGuid>68a5ffce-0ab2-439d-935e-42c826c7e432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='wizard-p-0']/div[8]/span/span/span/span</value>
      <webElementGuid>743326aa-28ea-4e20-8f8f-52570e407e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Jenjang'])[1]/following::span[4]</value>
      <webElementGuid>de4e80cc-f11f-4473-8a07-8a07231dad47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paket Kilat - (4 Sesi Offline) - Rp200.000/sesi - Total = Rp800.000'])[3]/following::span[4]</value>
      <webElementGuid>e739df33-5edb-4171-b684-ceea6c64dc48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilihan hari'])[1]/preceding::span[3]</value>
      <webElementGuid>95d4bd46-7b08-4b29-b20e-b5148ac69a66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Senin'])[1]/preceding::span[3]</value>
      <webElementGuid>792f8ca6-6107-4a3a-a058-f82d46b158d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/span/span/span/span</value>
      <webElementGuid>6363318f-c307-48c2-8899-6919fdb3cb72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-reward_form_submission_submission_data_les_jenjang-container' and @title = 'Pilih Jenjang' and (text() = 'Pilih Jenjang' or . = 'Pilih Jenjang')]</value>
      <webElementGuid>585eac11-957c-453d-b0ed-4bc9f5d2de4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
