<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Orang Tua</name>
   <tag></tag>
   <elementGuidId>47335ca9-237e-4117-b1ec-d0f97de01465</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-reward_form_submission_submission_data_role_rgprivat-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-reward_form_submission_submission_data_role_rgprivat-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>35a0c2a5-261a-4883-ab2c-354a1471057e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>56759cee-6524-4a5e-89cf-3bfa2f425f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-reward_form_submission_submission_data_role_rgprivat-container</value>
      <webElementGuid>3232feb4-8061-4ab1-aadf-a30e65e7700c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>4aac218e-3734-407d-8181-10d4a7fef872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4d27c4ad-8418-4386-85f1-c860355c3a06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Orang Tua</value>
      <webElementGuid>d2a0000a-1a28-4e03-bab2-13119c622614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Orang Tua</value>
      <webElementGuid>bda7783e-0771-49bd-8e5d-2cbe3c20f41c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-reward_form_submission_submission_data_role_rgprivat-container&quot;)</value>
      <webElementGuid>9116f130-3545-4e21-baac-205548e4eb52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-reward_form_submission_submission_data_role_rgprivat-container']</value>
      <webElementGuid>d23f02d3-232d-4b78-828b-ed8825b41cef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='wizard-p-0']/div[13]/span/span/span/span</value>
      <webElementGuid>8f06a537-d357-4aa2-99b8-c752fa0841fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar sebagai'])[1]/following::span[4]</value>
      <webElementGuid>0d23b449-5e60-4107-aaf6-16c863b4579d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe pengajar lainnya'])[1]/following::span[4]</value>
      <webElementGuid>0a668e06-8f71-4319-ba89-ae8617a3b365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Kontak'])[1]/preceding::span[3]</value>
      <webElementGuid>993a760a-93a7-4a63-88bb-fc4b481ac092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama lengkap'])[1]/preceding::span[3]</value>
      <webElementGuid>ec1e51cc-2722-4c5a-a12c-5588d815c145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/span/span/span/span</value>
      <webElementGuid>d261a1a3-1f75-43f1-84a7-99ddfea87728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-reward_form_submission_submission_data_role_rgprivat-container' and @title = 'Orang Tua' and (text() = 'Orang Tua' or . = 'Orang Tua')]</value>
      <webElementGuid>f9f4de09-1254-4550-99d6-7f33b021143f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
