<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Bahasa Indonesia</name>
   <tag></tag>
   <elementGuidId>7735a3bb-ecec-489c-870b-0810a8ec27f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-reward_form_submission_submission_data_les_academic-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-reward_form_submission_submission_data_les_academic-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9bf43fe1-6f54-44e8-917a-41358a5bf1f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>5aaa23d2-0a96-466c-a1e0-28acfecd7139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-reward_form_submission_submission_data_les_academic-container</value>
      <webElementGuid>46294f86-7fb2-4013-b3dc-77cb6467f537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>ee95f090-a56e-4e1c-9964-6097bd519d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0ad09efc-0a6c-488b-92a7-53d4da7d268a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Bahasa Indonesia</value>
      <webElementGuid>eee0971c-ef01-495b-af03-33cf846e520d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bahasa Indonesia</value>
      <webElementGuid>6dcde2c7-88fb-4c75-b1d4-7906e451a820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-reward_form_submission_submission_data_les_academic-container&quot;)</value>
      <webElementGuid>b93cf4f7-faa4-48c1-b4ea-d2a3316cd065</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-reward_form_submission_submission_data_les_academic-container']</value>
      <webElementGuid>4f82afb1-8975-42d0-a44a-852d8137f2f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='wizard-p-0']/div[2]/span/span/span/span</value>
      <webElementGuid>8645e2d5-5dd3-43e4-be43-5dd8ecdc4938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Mapel:'])[1]/following::span[4]</value>
      <webElementGuid>2c0a330f-9da4-4040-a6bb-d72c7d3398ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paket For Kids'])[1]/following::span[4]</value>
      <webElementGuid>860ee1fe-65ec-41d9-ad4d-879cc4c4c629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Mapel:'])[2]/preceding::span[3]</value>
      <webElementGuid>40b47f9d-09af-466e-830e-3aba2b6d4d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Mapel'])[3]/preceding::span[3]</value>
      <webElementGuid>648a7a08-a9ca-4f69-b27f-357e89a4327c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>883624ba-fab8-4b6b-a95b-d926ffd26930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-reward_form_submission_submission_data_les_academic-container' and @title = 'Bahasa Indonesia' and (text() = 'Bahasa Indonesia' or . = 'Bahasa Indonesia')]</value>
      <webElementGuid>4d4cf76a-eb62-468d-8eae-86878d260ff4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
