<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pilih Mapel_1</name>
   <tag></tag>
   <elementGuidId>cb6d5ee4-eaed-422c-86f6-826b30355c09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-reward_form_submission_submission_data_les_academic-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-reward_form_submission_submission_data_les_academic-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>688864b5-6a45-4045-99e9-754cbd1e59a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>8495b07b-b57f-4130-b09b-379181e75062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-reward_form_submission_submission_data_les_academic-container</value>
      <webElementGuid>cf9e5459-ad36-46cb-ad63-ff1f0c3aed6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>f17b7c5a-2792-47db-ba0d-66b8c9d2a5f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>be56e8b8-ce22-4aa2-ac80-0f807616093b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Pilih Mapel</value>
      <webElementGuid>f11fbd69-423d-4240-8612-f9c18f164237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Mapel</value>
      <webElementGuid>e13f25a7-7d7a-43d2-93ad-508b870159e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-reward_form_submission_submission_data_les_academic-container&quot;)</value>
      <webElementGuid>b641eaca-4ff5-496c-8821-e8109ab6f769</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-reward_form_submission_submission_data_les_academic-container']</value>
      <webElementGuid>4a647447-3253-4e35-a125-24d72ce772f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='wizard-p-0']/div[2]/span/span/span/span</value>
      <webElementGuid>bde7bb6c-31ef-487a-a247-2a7ced16ed7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Mapel:'])[1]/following::span[4]</value>
      <webElementGuid>182f968a-f2b5-4a40-a83b-93acdf7cb3f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paket For Kids'])[1]/following::span[4]</value>
      <webElementGuid>b7bb4723-d800-420d-b6d0-3b43debd3bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Mapel:'])[2]/preceding::span[3]</value>
      <webElementGuid>45aaf73a-eb46-4e89-b58f-53ba6da10806</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Mapel'])[4]/preceding::span[3]</value>
      <webElementGuid>17f345fd-6a42-4e53-91ee-3675968460fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>a280a0b3-c282-40d7-bde4-5497c43d82fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-reward_form_submission_submission_data_les_academic-container' and @title = 'Pilih Mapel' and (text() = 'Pilih Mapel' or . = 'Pilih Mapel')]</value>
      <webElementGuid>2ba9a05d-2600-44c3-80a0-509f8f589dbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
