<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Kelas 2</name>
   <tag></tag>
   <elementGuidId>7d6effaf-e8ea-4848-8f43-c55817e6cc20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@value='1-2'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cf857723-0d06-4e1a-a9c7-f8363e0c35dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tabs-package</value>
      <webElementGuid>b35d087e-97b9-4d17-baaa-b1beb518589e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>c01420fc-9480-49c3-8cdf-62744e632c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1-2</value>
      <webElementGuid>c78ee7c9-da80-4e3c-9ae3-33ae00448a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kelas 2</value>
      <webElementGuid>444c29a8-3cb2-41f3-a391-9358498f8468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabPaket&quot;)/div[@class=&quot;nav-package&quot;]/nav[1]/button[@class=&quot;tabs-package&quot;]</value>
      <webElementGuid>3cdba374-5ee3-42d1-8dd8-8579df333f2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@value='1-2'])[2]</value>
      <webElementGuid>675f6a23-5002-41eb-9746-0900e0d1e105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabPaket']/div/nav/button[2]</value>
      <webElementGuid>fc20a7fe-0e65-4569-858d-879ee1aeb546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelas 1'])[1]/following::button[1]</value>
      <webElementGuid>0b2787a5-d300-4aa0-847c-bfa5f00cc1f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Fitur'])[1]/following::button[2]</value>
      <webElementGuid>16f198fa-d077-4d43-b5c5-4d5f9abc553e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelas 3'])[1]/preceding::button[1]</value>
      <webElementGuid>14fd076d-54ea-40dc-b9b4-910eaf5d39cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelas 4'])[1]/preceding::button[2]</value>
      <webElementGuid>16e62190-0777-4a4a-8608-06b442f815a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kelas 2']/parent::*</value>
      <webElementGuid>d75963ec-0055-4263-952e-986ab90780a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>9df3d807-8ac6-49cf-9636-79e85835e00a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Kelas 2' or . = 'Kelas 2')]</value>
      <webElementGuid>23c992e4-48b7-4416-9d3f-70a1d57f2b39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
