<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Apakah kamu sudah memiliki akun Ruang_a83efd</name>
   <tag></tag>
   <elementGuidId>dba26e3e-ef67-46d5-b281-b5e64d32662c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#apakah_kamu_sudah_memiliki_account_ruangguru___kode_referral__-input-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='apakah_kamu_sudah_memiliki_account_ruangguru___kode_referral__-input-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6fb00176-e392-40a2-b0c6-45c76b08e9ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apakah_kamu_sudah_memiliki_account_ruangguru___kode_referral__-input-1</value>
      <webElementGuid>d571235c-702d-46b0-9534-67e50fa51b85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hs-form__field__input hs-form__field__radio__input</value>
      <webElementGuid>18f29ad8-80aa-46ba-ad6e-21b8a5a72ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a2a5e427-4e74-48f8-af98-4f6012d00d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>apakah_kamu_sudah_memiliki_account_ruangguru___kode_referral__</value>
      <webElementGuid>80de7ccf-943d-4b0e-8e10-c00a2682b7b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2e46e77b-180c-4fad-b34b-09760c688aab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>apakah_kamu_sudah_memiliki_account_ruangguru___kode_referral__-label-1</value>
      <webElementGuid>56415e2e-96ee-4321-9c0b-a873fbaa5b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>apakah_kamu_sudah_memiliki_account_ruangguru___kode_referral__-description</value>
      <webElementGuid>1bd8d367-0e2f-4a1d-ad8d-12b8e93daa76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>397c7667-0009-4779-b3ce-653bac13b310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dcfb391f-43ed-4091-9d9c-7a49752bae54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sudah</value>
      <webElementGuid>09599db2-c5a3-44c0-a5fe-3d9818d7bed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apakah_kamu_sudah_memiliki_account_ruangguru___kode_referral__-input-1&quot;)</value>
      <webElementGuid>df05686d-8148-4364-8649-712cc323e19a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='apakah_kamu_sudah_memiliki_account_ruangguru___kode_referral__-input-1']</value>
      <webElementGuid>42facbd4-93b1-4765-a212-f0549bd6582b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='apakah_kamu_sudah_memiliki_account_ruangguru___kode_referral__-label-1']/input</value>
      <webElementGuid>0949fefe-cbc6-405b-a2b5-4db3df951c84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>be92f52c-37ee-468c-a0c9-2613d94e247d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'apakah_kamu_sudah_memiliki_account_ruangguru___kode_referral__-input-1' and @type = 'radio' and @name = 'apakah_kamu_sudah_memiliki_account_ruangguru___kode_referral__']</value>
      <webElementGuid>59daa679-ce7a-4e01-bf46-3aaa752909c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
