<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tidak_saya_telah_membaca_dan_menyetuj_36fb98</name>
   <tag></tag>
   <elementGuidId>dc37f2f9-8594-4807-8cac-a87736f5273c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#saya_telah_membaca_dan_menyetujui_syarat_dan_ketentuan_khusus_program_sahabat_ruangguru-input-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='saya_telah_membaca_dan_menyetujui_syarat_dan_ketentuan_khusus_program_sahabat_ruangguru-input-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9306391a-5a7e-4808-a3de-42ddf9726985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>saya_telah_membaca_dan_menyetujui_syarat_dan_ketentuan_khusus_program_sahabat_ruangguru-input-1</value>
      <webElementGuid>7aeb7c05-daa8-46a1-80ef-92ef5c0f13cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hs-form__field__input hs-form__field__checkbox__input</value>
      <webElementGuid>54f9a232-ebd6-4bf3-81da-07531aa1a8cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6da5a664-4475-4773-a57c-3b643d0af0cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>saya_telah_membaca_dan_menyetujui_syarat_dan_ketentuan_khusus_program_sahabat_ruangguru</value>
      <webElementGuid>98dce3e4-b3c5-4c83-afad-848205e9231d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>56f2bfdb-9fc5-4803-a66d-a2515d89a80b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>saya_telah_membaca_dan_menyetujui_syarat_dan_ketentuan_khusus_program_sahabat_ruangguru-label-1</value>
      <webElementGuid>7608373a-7465-4e12-9db7-2d5dbabc57e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>saya_telah_membaca_dan_menyetujui_syarat_dan_ketentuan_khusus_program_sahabat_ruangguru-description</value>
      <webElementGuid>9af265fe-bf87-49c5-8700-b2e3403980ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4c6d1e40-0660-42ec-b84b-a3b83e1c23c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e00f2115-6676-4a78-a57c-624ff514864a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;saya_telah_membaca_dan_menyetujui_syarat_dan_ketentuan_khusus_program_sahabat_ruangguru-input-1&quot;)</value>
      <webElementGuid>ab3cecea-ae9f-44c5-ac15-1e7baf3dbfa0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='saya_telah_membaca_dan_menyetujui_syarat_dan_ketentuan_khusus_program_sahabat_ruangguru-input-1']</value>
      <webElementGuid>a2ba460a-0bae-4c94-924b-b1de2ec3e636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='saya_telah_membaca_dan_menyetujui_syarat_dan_ketentuan_khusus_program_sahabat_ruangguru-label-1']/input</value>
      <webElementGuid>589ded15-8dbd-4d3f-a128-205b7b496b91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div/div/div/label/input</value>
      <webElementGuid>bb975cf0-38b4-47e0-8637-7f7741e37a81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'saya_telah_membaca_dan_menyetujui_syarat_dan_ketentuan_khusus_program_sahabat_ruangguru-input-1' and @type = 'checkbox' and @name = 'saya_telah_membaca_dan_menyetujui_syarat_dan_ketentuan_khusus_program_sahabat_ruangguru']</value>
      <webElementGuid>810252fb-ac3b-4288-9626-c5cbdf5af3f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
