<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mohon diisi sesuai dengan email aktif_a97e45</name>
   <tag></tag>
   <elementGuidId>63419301-9693-470d-90b1-80a8dcea7d5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#email-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='email-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>31b4044d-ff84-4190-be6f-bfa27305a143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email-input</value>
      <webElementGuid>ce4c7c51-7360-4f5d-9bf8-fb77a8fc800d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hs-form__field__input</value>
      <webElementGuid>08c43354-ed0e-4dd7-8c4c-9fe17b82322f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>fa263903-e22d-44a2-82b1-a9a920ff5cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>1cf2ba4f-5b9a-4827-ad70-e68c4b44f318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>84aeb5b1-3282-4e6a-90ad-9ae6ee2d2bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>63e72232-3ca0-4594-8a50-41a92ae0112c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4276f191-3c26-4059-a050-e17e46736fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>email-label</value>
      <webElementGuid>4a510e14-e554-47e3-979a-484138b1d65d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>email-description</value>
      <webElementGuid>792bf348-219e-4f7a-af9f-c5c8eee8033c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>500fc90f-3506-492d-9768-087d6d3e23dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>V</value>
      <webElementGuid>38aa7065-a981-4b08-b97e-8709ece65a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email-input&quot;)</value>
      <webElementGuid>572fff91-a288-42de-ab5c-49e0fada2e0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='email-input']</value>
      <webElementGuid>dec22b31-224b-4f22-b1ae-ab834b7d963d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='hs-form-f0ed10a8-47b0-4c6f-972d-5cb8018ff964-c5232c3c-2f9e-48f9-bc1c-a79a01cebb56']/div/div[6]/div/div/div/div/input</value>
      <webElementGuid>f7ddcba3-95c5-4bda-834d-e43a8065e1d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/input</value>
      <webElementGuid>7308d4ff-01be-4bfc-80e8-e7e8d30be012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'email-input' and @type = 'email' and @name = 'email']</value>
      <webElementGuid>61e7a14f-4b5e-4557-b560-487ec5f2fb8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
