<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username Akun Social Media Kamu_social_media</name>
   <tag></tag>
   <elementGuidId>1f88e8a1-8396-4f9b-a5ed-a220601dfad4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#social_media-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='social_media-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7291d29c-e8c7-4902-bc89-9c11f944a845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>social_media-input</value>
      <webElementGuid>12e0fe12-a501-4ec3-ace4-728cb3a07c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hs-form__field__input</value>
      <webElementGuid>8b481d65-61db-4f8b-be8f-dcde56811052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5db07de1-502e-47de-86a3-45be6a92993b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>social_media</value>
      <webElementGuid>21e8e99f-3b13-43bb-ab45-14273d8eda42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bba274b6-62da-4163-9617-692dbadc8759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9b5fd7d9-aae1-4e7d-b66f-3619f22f8488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>social_media-label</value>
      <webElementGuid>97d8cabc-66ff-4d2b-bfba-93cb95267599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>social_media-description</value>
      <webElementGuid>d2f975f9-50ea-4e9a-aa64-7b00c81e92b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bdae74b4-cd77-4cf6-a40f-e0371be27cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;social_media-input&quot;)</value>
      <webElementGuid>56c8b924-cf60-4243-a636-42c838414cb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='social_media-input']</value>
      <webElementGuid>eb82082b-19b4-4684-bc46-9735ebba45b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='hs-form-f0ed10a8-47b0-4c6f-972d-5cb8018ff964-c5232c3c-2f9e-48f9-bc1c-a79a01cebb56']/div/div[9]/div/div/div/div/input</value>
      <webElementGuid>6faa31b9-894d-4e80-ae42-e0a3cc405e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/div/input</value>
      <webElementGuid>4ade7cfb-8c31-42f1-8c76-72dc57214bdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'social_media-input' and @type = 'text' and @name = 'social_media']</value>
      <webElementGuid>6812752f-97f4-4cde-a05b-ba02d0ee8fe6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
