<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama_firstname</name>
   <tag></tag>
   <elementGuidId>a8fa5e0f-0363-480b-90a3-ce146e8454f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#firstname-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='firstname-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>81444f6e-0be2-4653-9278-3bb6d7a2385a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>firstname-input</value>
      <webElementGuid>4af80ecf-2a26-4007-82a3-214ab58cea84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hs-form__field__input</value>
      <webElementGuid>1b78e5df-6498-459d-9213-50d6ea2b5b3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d4778d9d-1162-46da-8783-945ef70714d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>firstname</value>
      <webElementGuid>0956706a-b499-4361-a7ec-18624f2a9e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>given-name</value>
      <webElementGuid>f4305492-369a-4291-982c-63f6273339d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ccca480a-8fc0-45bf-a754-8fd836a0c577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9b977b44-9853-4217-92ee-a279be657c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>firstname-label</value>
      <webElementGuid>f1be844f-b4f0-4d74-8d84-2fb06b037110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>firstname-description</value>
      <webElementGuid>4ef879d3-9321-4ddc-85ae-e47b4bc74749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>706bd421-ac7e-423f-ab15-62af82e1ea26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>V</value>
      <webElementGuid>2a9a0f82-8cc1-47ad-ad37-cc984bb02075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;firstname-input&quot;)</value>
      <webElementGuid>f30760dd-8810-423d-a53f-9f38591c14ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='firstname-input']</value>
      <webElementGuid>e1590c71-cb6f-4e6c-b505-d9d6420e0374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='hs-form-f0ed10a8-47b0-4c6f-972d-5cb8018ff964-c5232c3c-2f9e-48f9-bc1c-a79a01cebb56']/div/div[5]/div/div/div/div/input</value>
      <webElementGuid>dec36071-67ed-43bf-8d66-1ecede07b613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>73949c21-2aa8-4ce7-8502-6ba5656662bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'firstname-input' and @type = 'text' and @name = 'firstname']</value>
      <webElementGuid>9ead36d0-a318-4da0-a4b9-c02ff4acef2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
