<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sudah_apakah_kamu_sudah_memiliki_acco_755d60</name>
   <tag></tag>
   <elementGuidId>cb13d169-294c-4549-8ba4-d958e20a4a76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#apakah_kamu_sudah_memiliki_account_ruangguru___kode_referral__-input-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='apakah_kamu_sudah_memiliki_account_ruangguru___kode_referral__-input-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dd7e8c26-fe59-42bf-b394-d532f73a429c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apakah_kamu_sudah_memiliki_account_ruangguru___kode_referral__-input-2</value>
      <webElementGuid>cb00370e-245b-40fb-a224-6736dc83074d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hs-form__field__input hs-form__field__radio__input</value>
      <webElementGuid>b14d003a-12ce-416d-8e60-67ad55024a0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>5bd277bc-452c-4bbd-97b0-42c3e9a0acb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>apakah_kamu_sudah_memiliki_account_ruangguru___kode_referral__</value>
      <webElementGuid>fa54cf4c-7c40-4f0f-8efe-be344eaf6472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fb887de0-a2fd-44c8-af3b-c7955d407343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>apakah_kamu_sudah_memiliki_account_ruangguru___kode_referral__-label-2</value>
      <webElementGuid>e8c570ac-1c30-411d-b58a-24e6f5995ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>apakah_kamu_sudah_memiliki_account_ruangguru___kode_referral__-description</value>
      <webElementGuid>50833e86-1aa9-4721-a6b1-8c2763fd8e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a34c7f5c-8e55-40ae-b7b1-108cbc03d054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c84ac991-2c76-44b6-b922-94ae5c32c742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Belum</value>
      <webElementGuid>d8cc0a4a-9d31-4acd-8937-1382994aceae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apakah_kamu_sudah_memiliki_account_ruangguru___kode_referral__-input-2&quot;)</value>
      <webElementGuid>2d89e5e4-51e8-4ab9-8445-4c55c19676e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='apakah_kamu_sudah_memiliki_account_ruangguru___kode_referral__-input-2']</value>
      <webElementGuid>c278ba13-5556-4cc7-8373-33d57180b81d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='apakah_kamu_sudah_memiliki_account_ruangguru___kode_referral__-label-2']/input</value>
      <webElementGuid>4dd162a0-6576-44e5-a20e-3e088919447f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/input</value>
      <webElementGuid>f4a16a29-7072-4dfb-a44f-7a38d582502c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'apakah_kamu_sudah_memiliki_account_ruangguru___kode_referral__-input-2' and @type = 'radio' and @name = 'apakah_kamu_sudah_memiliki_account_ruangguru___kode_referral__']</value>
      <webElementGuid>aa24ff7b-bf90-405a-9b24-675f7d638894</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
