<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Belum_apakah_anda_bekerja_sebagai_peg_8905cc</name>
   <tag></tag>
   <elementGuidId>cd48f020-9c7d-4dcd-980a-b6190f3e46fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#apakah_anda_bekerja_sebagai_pegawai_negeri_sesuai_undang_undang_kepegawaian_dan_atau_menerima_gaji_-input-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='apakah_anda_bekerja_sebagai_pegawai_negeri_sesuai_undang_undang_kepegawaian_dan_atau_menerima_gaji_-input-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d871620-6d1a-4765-b84c-6776dda69653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apakah_anda_bekerja_sebagai_pegawai_negeri_sesuai_undang_undang_kepegawaian_dan_atau_menerima_gaji_-input-1</value>
      <webElementGuid>46e77092-044b-4252-a76a-217fceb3741d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hs-form__field__input hs-form__field__radio__input</value>
      <webElementGuid>c95d8333-db41-45b4-86de-2afc35dfe2b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ed14453e-94b3-4d9f-af08-82b6be42035a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>apakah_anda_bekerja_sebagai_pegawai_negeri_sesuai_undang_undang_kepegawaian_dan_atau_menerima_gaji_</value>
      <webElementGuid>80070905-7f4c-4f9e-8c75-6d8bece081ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f8170eaf-4fdd-4ff4-b820-6fd3cd661829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>apakah_anda_bekerja_sebagai_pegawai_negeri_sesuai_undang_undang_kepegawaian_dan_atau_menerima_gaji_-label-1</value>
      <webElementGuid>b1223d09-ce3c-4109-b115-a425c9ed6ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>apakah_anda_bekerja_sebagai_pegawai_negeri_sesuai_undang_undang_kepegawaian_dan_atau_menerima_gaji_-description</value>
      <webElementGuid>7a767cf1-de8e-45e7-84ca-63fd71212100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f782352e-d63f-482b-9cde-34fd9b1c8b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bde28fb0-3afe-4668-b10f-bbef7c7b6eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ya</value>
      <webElementGuid>0676076a-5931-4746-8ae2-e0a15cc69876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apakah_anda_bekerja_sebagai_pegawai_negeri_sesuai_undang_undang_kepegawaian_dan_atau_menerima_gaji_-input-1&quot;)</value>
      <webElementGuid>e24a6e1f-000a-4745-bd09-3f86f58f9e43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='apakah_anda_bekerja_sebagai_pegawai_negeri_sesuai_undang_undang_kepegawaian_dan_atau_menerima_gaji_-input-1']</value>
      <webElementGuid>d140cfc5-1c5c-4e57-9174-b457d38c1b14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='apakah_anda_bekerja_sebagai_pegawai_negeri_sesuai_undang_undang_kepegawaian_dan_atau_menerima_gaji_-label-1']/input</value>
      <webElementGuid>3d40e8bb-f2b9-4746-b68e-6359e3150174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/div/div/div/div/div/label/input</value>
      <webElementGuid>10342b75-3a7d-42be-8f56-f451130d0a00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'apakah_anda_bekerja_sebagai_pegawai_negeri_sesuai_undang_undang_kepegawaian_dan_atau_menerima_gaji_-input-1' and @type = 'radio' and @name = 'apakah_anda_bekerja_sebagai_pegawai_negeri_sesuai_undang_undang_kepegawaian_dan_atau_menerima_gaji_']</value>
      <webElementGuid>290782f9-272e-4791-b99e-265186d24169</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
