<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor HP (Terhubung ke Whatsapp)_phone</name>
   <tag></tag>
   <elementGuidId>e0bc8b57-4838-4798-a86c-7e48ef51830e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#phone-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='phone-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ab31452-8e0a-4e9e-b191-5b605b858a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phone-input</value>
      <webElementGuid>6a9dd2f8-3bf5-4899-8d47-e26635aa6bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hs-form__field__input</value>
      <webElementGuid>83635e67-80c7-4c0f-8933-8ff13e51afdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>24638925-b6d7-4c5d-83aa-564de0de4f03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>ce659ad6-006d-4ef7-80e9-2861857918bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>72f6bba6-9b9d-41d8-902a-4148a90ff5b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>aebfc61b-af33-4933-a55b-5cd4cae3989f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>134006fc-4cf0-44cb-b849-74acf3bc98a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>phone-label</value>
      <webElementGuid>8f9870c9-3445-40bb-83c5-122cd74541c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>phone-description</value>
      <webElementGuid>115b615d-a252-4763-9afe-d6c752aa095e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4292da5f-aea3-4cfb-bd18-758c3e94939d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>62b9b2e1-97c8-4520-86de-40526c7bc964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phone-input&quot;)</value>
      <webElementGuid>6ee17f93-bb4a-404a-bf98-5655ca18f5dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='phone-input']</value>
      <webElementGuid>0a3059c8-e410-4f39-98bf-a28e9e0549d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='hs-form-f0ed10a8-47b0-4c6f-972d-5cb8018ff964-c5232c3c-2f9e-48f9-bc1c-a79a01cebb56']/div/div[7]/div/div/div/div/div/input</value>
      <webElementGuid>17801e14-61f9-4e41-b8af-d3968b3bcc4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/div/input</value>
      <webElementGuid>b9fe7c19-1249-476f-871a-ca1330b2f128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'phone-input' and @type = 'tel' and @name = 'phone']</value>
      <webElementGuid>9f51279a-a5e0-4c81-b61d-81d0f7261d9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
