<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please SelectSiswa SD-SMAMahasiswaIb_fd9846</name>
   <tag></tag>
   <elementGuidId>a80495a2-a5aa-4ff2-95c1-049db5adcd82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pekerjaan_utama_saat_ini-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='pekerjaan_utama_saat_ini-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5d38bc27-df2c-4db7-9e1a-8188267a8800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pekerjaan_utama_saat_ini-input</value>
      <webElementGuid>67a44ff2-8942-4fef-b2e9-492c660d056f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hs-form__field__input is-placeholder</value>
      <webElementGuid>e62a086d-8e3f-4d8a-9e06-df9828579aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pekerjaan_utama_saat_ini</value>
      <webElementGuid>9f62d770-044c-4e68-9ce4-9f12e5d1fd87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>eb38d848-7e44-4a00-b00b-f32415e0c08e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>pekerjaan_utama_saat_ini-label</value>
      <webElementGuid>f68d6690-a11e-4158-98d2-16952cac6ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>pekerjaan_utama_saat_ini-description</value>
      <webElementGuid>f9ceaa39-e41d-4e04-a9fd-f2b1beeb5dd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>36cdfa98-d171-4673-9f3d-e0ca31014cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please SelectSiswa SD-SMAMahasiswaIbu/Bapak rumah tanggaContent creator, contoh: Youtuber/Tiktoker/Blogger/InfluencerKaryawan swastaPengusaha/pelaku UMKMFreelancer/pekerja lepas/ojek onlinePegawai Negeri, contoh: Guru/TNI/PolisiKaryawan BUMNPensiun</value>
      <webElementGuid>38fc5682-cccc-47d4-9190-c2658921fac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pekerjaan_utama_saat_ini-input&quot;)</value>
      <webElementGuid>1605fa62-7311-4a14-934c-82909a47ade9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='pekerjaan_utama_saat_ini-input']</value>
      <webElementGuid>7b08b98f-c4dc-446c-bf25-6078a9604d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='hs-form-f0ed10a8-47b0-4c6f-972d-5cb8018ff964-c5232c3c-2f9e-48f9-bc1c-a79a01cebb56']/div/div[8]/div/div/div/div/select</value>
      <webElementGuid>63a59715-06d1-443c-919b-8c7f60f1fe89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pekerjaan utama saat ini'])[1]/following::select[1]</value>
      <webElementGuid>ccf7769e-ac8c-4ae1-bb51-9b8d9794b46c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor HP (Terhubung ke Whatsapp)'])[1]/following::select[1]</value>
      <webElementGuid>e09bb3ae-5d34-4310-be0a-8e73a216da1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username Akun Social Media Kamu'])[1]/preceding::select[1]</value>
      <webElementGuid>41be2199-a018-4df5-a5d5-907a212981c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apakah kamu sudah memiliki akun Ruangguru dan Kode Referral Sahabat Ruangguru?'])[1]/preceding::select[1]</value>
      <webElementGuid>bc10556a-e941-47af-af5e-f0733b3a9e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>7895f370-17fc-4388-bee3-5c3bd27bfc84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'pekerjaan_utama_saat_ini-input' and @name = 'pekerjaan_utama_saat_ini' and (text() = 'Please SelectSiswa SD-SMAMahasiswaIbu/Bapak rumah tanggaContent creator, contoh: Youtuber/Tiktoker/Blogger/InfluencerKaryawan swastaPengusaha/pelaku UMKMFreelancer/pekerja lepas/ojek onlinePegawai Negeri, contoh: Guru/TNI/PolisiKaryawan BUMNPensiun' or . = 'Please SelectSiswa SD-SMAMahasiswaIbu/Bapak rumah tanggaContent creator, contoh: Youtuber/Tiktoker/Blogger/InfluencerKaryawan swastaPengusaha/pelaku UMKMFreelancer/pekerja lepas/ojek onlinePegawai Negeri, contoh: Guru/TNI/PolisiKaryawan BUMNPensiun')]</value>
      <webElementGuid>79b95ab2-bd9d-4cf8-a760-cd953b9ab302</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
