<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lihat Detail</name>
   <tag></tag>
   <elementGuidId>86c1e634-e021-43f7-ba41-3b2fae559739</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-cards']/div[3]/div[5]/div[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b0dc1f10-b54f-4818-b9dc-45919e9bfe3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.ruangguru.com/program/sahabat</value>
      <webElementGuid>5c008701-77de-447a-97b9-2c8bee69c681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lihat Detail</value>
      <webElementGuid>4809c06a-3ec8-4fe0-8d1e-bc669159aeaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-cards&quot;)/div[@class=&quot;content-card&quot;]/div[@class=&quot;card-event show&quot;]/div[@class=&quot;card-button pt-0&quot;]/a[1]</value>
      <webElementGuid>d276f6d2-7d69-499e-9ef1-146cf1df1419</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-cards']/div[3]/div[5]/div[3]/a</value>
      <webElementGuid>a00333cc-9f37-453a-969e-eacf2b0e7e5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Lihat Detail')])[5]</value>
      <webElementGuid>5b3c3db1-1da6-43de-959f-96c4fe51a8c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sahabat Ruangguru'])[1]/following::a[1]</value>
      <webElementGuid>5565b0d8-975f-4f12-9912-b3f39b9d9f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Detail'])[4]/following::a[3]</value>
      <webElementGuid>50f8d6d7-8dee-413a-bf93-65bd117eff80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ruangguru x Kampus Merdeka'])[1]/preceding::a[2]</value>
      <webElementGuid>48326262-2b4a-45a9-aaad-8ca7104b7db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Detail'])[6]/preceding::a[3]</value>
      <webElementGuid>84403b81-79fe-459a-bc2b-f9dc6e4aa2a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.ruangguru.com/program/sahabat')])[3]</value>
      <webElementGuid>bfcc1abf-c89f-4944-a7ca-a4b04ebdddad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/a</value>
      <webElementGuid>afd8d15a-79a2-475c-9150-c3188a8cacaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.ruangguru.com/program/sahabat' and (text() = 'Lihat Detail' or . = 'Lihat Detail')]</value>
      <webElementGuid>87f4d5af-59eb-4ec2-bd62-97877a0b464c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
