<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lihat Semua Bab</name>
   <tag></tag>
   <elementGuidId>8744feaa-6764-4c0a-bb81-fba145a6f610</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='topicLink']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#topicLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>841d4d0e-b0aa-4641-b97e-33c2671f552f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ruangguru.onelink.me/blPk/kt9zu6po?school_level_serial=4PDC6KCUYL&amp;school_level_general_serial=4PDC6KCUYL&amp;school_level_name=4PDC6KCUYL&amp;lesson_serial=4PDC6KCUYL&amp;lesson_general_serial=4PDC6KCUYL&amp;lesson_display_name=Biologi&amp;lesson_icon_url=https://imgix3.ruangguru.com/assets/ruang_belajar/icon/subject/subj_biologi.png&amp;topic_serial=E8L48A9G69</value>
      <webElementGuid>2f981632-2c89-4f18-bbbf-ca2888f88b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>topicLink</value>
      <webElementGuid>ae158c6b-9c9c-4f10-b1e6-7667bae294a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>cf2f87e1-fc35-439b-8edb-0a49360f5b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lihat Semua Bab
                    </value>
      <webElementGuid>24ab129a-b23b-4ae9-bf74-02699fc81346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topicLink&quot;)</value>
      <webElementGuid>d7ba046b-37ee-4eb7-8a71-d01bf4b92b05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='topicLink']</value>
      <webElementGuid>f243c7db-8147-403a-9469-2e5a6f562225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='video-simulation']/div[3]/div[2]/a</value>
      <webElementGuid>7100bdf1-f6ec-4761-b9f9-b52560613df0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lihat Semua Bab')]</value>
      <webElementGuid>e5c6640c-dddb-42dc-9a3d-c59eb9ab7ed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transpor Membran'])[1]/following::a[1]</value>
      <webElementGuid>d03de804-0009-46ed-b4cf-e5f0a58c635d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organel Sel'])[1]/following::a[1]</value>
      <webElementGuid>010ab2ef-c022-4d02-9b16-0cbfe7579b92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::a[1]</value>
      <webElementGuid>19cc8c91-bfb5-4df9-94d6-518a8850844c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelas 1 SD'])[2]/preceding::a[1]</value>
      <webElementGuid>5f0e33f7-4494-47c9-8846-f2f965935861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lihat Semua Bab']/parent::*</value>
      <webElementGuid>f29e6701-1f64-4d2b-a56b-ac320a69e89b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ruangguru.onelink.me/blPk/kt9zu6po?school_level_serial=4PDC6KCUYL&amp;school_level_general_serial=4PDC6KCUYL&amp;school_level_name=4PDC6KCUYL&amp;lesson_serial=4PDC6KCUYL&amp;lesson_general_serial=4PDC6KCUYL&amp;lesson_display_name=Biologi&amp;lesson_icon_url=https://imgix3.ruangguru.com/assets/ruang_belajar/icon/subject/subj_biologi.png&amp;topic_serial=E8L48A9G69')]</value>
      <webElementGuid>418ea813-8e1d-44b0-9d21-f96676d5bad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div[2]/a</value>
      <webElementGuid>f1f469cb-1fb3-436a-bc76-9cc9fc7899d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ruangguru.onelink.me/blPk/kt9zu6po?school_level_serial=4PDC6KCUYL&amp;school_level_general_serial=4PDC6KCUYL&amp;school_level_name=4PDC6KCUYL&amp;lesson_serial=4PDC6KCUYL&amp;lesson_general_serial=4PDC6KCUYL&amp;lesson_display_name=Biologi&amp;lesson_icon_url=https://imgix3.ruangguru.com/assets/ruang_belajar/icon/subject/subj_biologi.png&amp;topic_serial=E8L48A9G69' and @id = 'topicLink' and (text() = 'Lihat Semua Bab
                    ' or . = 'Lihat Semua Bab
                    ')]</value>
      <webElementGuid>12eb177d-f71e-419e-9ef8-97e3b31786ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
