<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SMA</name>
   <tag></tag>
   <elementGuidId>68712ffd-519e-480c-8631-f59204aa07a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@value='sma']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.button-basic-white.btn-grade-option.grade-sma.btn-grade-option-desktop.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d8cc11e0-721d-4012-8809-762df6a7e776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-basic-white btn-grade-option grade-sma btn-grade-option-desktop active</value>
      <webElementGuid>99fc275d-7785-4d4f-8990-2488101c086f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>sma</value>
      <webElementGuid>14bf5643-0a2a-4d68-9552-f74cea5097fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      SMA
    </value>
      <webElementGuid>8d94ebd5-6708-4495-b21b-65009f3ac08d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hs_cos_wrapper_module_166727521310287&quot;)/div[@class=&quot;grade-selector-section font-black&quot;]/div[@class=&quot;grade-selector-options&quot;]/button[@class=&quot;button-basic-white btn-grade-option grade-sma btn-grade-option-desktop active&quot;]</value>
      <webElementGuid>9deeff29-8e3c-4a76-9772-f726c4c9d6bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@value='sma']</value>
      <webElementGuid>d109c720-61a6-4672-8ec0-e54fcc28240d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hs_cos_wrapper_module_166727521310287']/div/div/button[3]</value>
      <webElementGuid>c4375685-b047-4c26-be26-038e933de9ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SMP'])[1]/following::button[1]</value>
      <webElementGuid>b93c50ca-9606-4dfa-9dba-ba8545be9e6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SD'])[1]/following::button[2]</value>
      <webElementGuid>720f4f64-498e-4953-b060-4502dac39794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UTBK/SNBT'])[1]/preceding::button[1]</value>
      <webElementGuid>81230184-44c0-40f8-8c28-e5984d34539d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SMA'])[2]/preceding::button[2]</value>
      <webElementGuid>88c4953c-7c69-4251-93a3-ae73b0d5be69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SMA']/parent::*</value>
      <webElementGuid>c3ad06ac-8218-4a14-80b9-e8daa1293596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>405b2c17-4cee-40c6-ab25-1281c00dde40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
      SMA
    ' or . = '
      SMA
    ')]</value>
      <webElementGuid>c37f7d76-ed07-4ad0-8676-82ebb3bde17f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
