<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Biologi</name>
   <tag></tag>
   <elementGuidId>284694a5-ad8f-44f6-8f21-be40486f5ca7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@value='sma-11-ipa-biologi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1d4d302d-5d66-4376-ae5b-35ab21b75f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0b1a82ce-af18-41ba-bf25-606f94ba36e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-lesson</value>
      <webElementGuid>9d1f5ca7-2924-42c7-b3b8-c8f3eb368385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>sma-11-ipa-biologi</value>
      <webElementGuid>7561fff2-e62a-4fda-be30-a9e69d70751c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-video-url</name>
      <type>Main</type>
      <value>https://youtube.com/embed/fqxKOF3k4nw</value>
      <webElementGuid>82c7b5c7-b9d7-4096-9fcf-d6ac58b02fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Biologi</value>
      <webElementGuid>826e0dfc-3217-4063-916b-b43f61abac40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chooseSubjectWrapper&quot;)/button[@class=&quot;btn-lesson&quot;]</value>
      <webElementGuid>732d0af9-4b02-4c05-b95c-ec00d4fd4f89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@value='sma-11-ipa-biologi']</value>
      <webElementGuid>19e2cfac-3539-458e-8c77-6939b8f2d7f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chooseSubjectWrapper']/button[2]</value>
      <webElementGuid>65ef0c72-dc4b-4514-976e-8b0beb8c88e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fisika'])[2]/following::button[1]</value>
      <webElementGuid>605b8789-6b4c-450f-b5ac-152e1390e37b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[2]/following::button[2]</value>
      <webElementGuid>dd7737c3-923e-4daa-8aae-5571153c25bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mau belajar lebih efektif?'])[1]/preceding::button[1]</value>
      <webElementGuid>85be7d82-2444-4d44-a952-34af3ba7562c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Contoh Gratis'])[1]/preceding::button[1]</value>
      <webElementGuid>4c3fcac1-9401-4a0d-83ce-615b9f382d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Biologi']/parent::*</value>
      <webElementGuid>300c95a1-795e-4c83-888a-1377308db757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/button[2]</value>
      <webElementGuid>37a7570e-9d51-4f11-a7c2-d80225b5c846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Biologi' or . = 'Biologi')]</value>
      <webElementGuid>10cc7e4c-2670-4f4a-ae91-3b54cabdf234</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
