<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>63c5bc6d-98f0-4d25-ac76-a3f843fd66eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hs_cos_wrapper_module_166727521310287']/div[2]/div/div/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;icon-close&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d4e8f090-532c-41c6-bd1c-32c18adceeb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.ruangguru.com/hubfs/Ruangguru%20Revamp%202022/Detail%20Page/Header/ic-close.svg</value>
      <webElementGuid>39150a08-fab5-4990-9760-7632e9f62b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icon-close</value>
      <webElementGuid>47198f7a-ecd8-4ef3-8330-ce65d4badf52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hs_cos_wrapper_module_166727521310287&quot;)/div[@class=&quot;modal-overlay modal-grade&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-grade-title&quot;]/button[@class=&quot;modal-close&quot;]/img[1]</value>
      <webElementGuid>e09b464d-6cea-4a0b-9901-da79c6c054f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hs_cos_wrapper_module_166727521310287']/div[2]/div/div/button/img</value>
      <webElementGuid>fe5e31b6-fe6a-4553-88a0-6bdb503115cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='icon-close']</value>
      <webElementGuid>f00ecf33-5fe5-4ff2-bb8c-4d0f3dad6c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button/img</value>
      <webElementGuid>f05c421a-cc37-4ab7-8372-cddfb37b1101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.ruangguru.com/hubfs/Ruangguru%20Revamp%202022/Detail%20Page/Header/ic-close.svg' and @alt = 'icon-close']</value>
      <webElementGuid>c4e4d5c5-321c-48b3-9c2d-c1c8db7cec8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
