<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Fisika</name>
   <tag></tag>
   <elementGuidId>f62384c2-bbe6-48ba-81bc-55d5e506bc86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>00</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selectedLessonNonSD</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>02504b1e-33f6-44fe-93fd-9babf6f533bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-inter font-black</value>
      <webElementGuid>3ce08937-ab02-4901-83fa-4f24466365e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectedLessonNonSD</value>
      <webElementGuid>5f2d2dfd-7042-47a9-915a-12618932107d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fisika</value>
      <webElementGuid>0b215378-8cce-466f-85dc-21fa68c0eb1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectedLessonNonSD&quot;)</value>
      <webElementGuid>1695166b-dd77-4126-a0da-436b4205f8eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='selectedLessonNonSD']</value>
      <webElementGuid>3913891d-6f70-4abd-b502-1505dae711e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='video-simulation']/div/div[3]/p[2]</value>
      <webElementGuid>01c8d5b8-b193-40eb-b3fa-c6990c9e84e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bisa pilih penjelasan yang detail atau cepat'])[1]/following::p[4]</value>
      <webElementGuid>7a817076-a343-4dcc-bff6-fc04815767c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Video belajar menyesuaikan pemahaman'])[1]/following::p[4]</value>
      <webElementGuid>775c2790-3124-4d9f-8d42-bb97debdf55c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tekanan'])[1]/preceding::p[3]</value>
      <webElementGuid>4b23f4fb-4a2b-4147-865f-ad8a7fb79cad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hukum Pokok Hidrostatis'])[1]/preceding::p[3]</value>
      <webElementGuid>0e87c4b0-6383-409e-b85d-2537bc8a5826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Fisika']/parent::*</value>
      <webElementGuid>1101c2dc-04d5-4516-b365-ad3b616f7efd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/p[2]</value>
      <webElementGuid>782d3d58-d26c-4226-bdcf-18987184b91d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'selectedLessonNonSD' and (text() = 'Fisika' or . = 'Fisika')]</value>
      <webElementGuid>11d45fb4-2014-426c-bbc4-cb17c2d2e629</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
