<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>2a102e50-9f05-4f8f-96fd-6bcf5387760e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='gradeNonSDCloseModal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gradeNonSDCloseModal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>019892bc-f7c7-4a17-b239-5356a49f9b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close-jenjang</value>
      <webElementGuid>e496f21e-a8cc-4f3c-aa08-ffbe80cba3a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gradeNonSDCloseModal</value>
      <webElementGuid>113db0c0-0e3c-4497-acb7-5ffc121148a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>473eb020-77d4-4e40-9911-1aaf2d916a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gradeNonSDCloseModal&quot;)</value>
      <webElementGuid>78e45254-9ca2-442d-8db7-ff86f8d38571</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='gradeNonSDCloseModal']</value>
      <webElementGuid>675a368f-5225-4f30-9edb-9be9da937bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gradeNonSDModal']/div/div/span</value>
      <webElementGuid>1acf89f8-c7ed-4b01-b7cc-9591c6093000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bisa pilih penjelasan yang detail atau cepat'])[1]/following::span[1]</value>
      <webElementGuid>fb036203-3e88-4c26-b64a-8ba52835d9c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Video belajar menyesuaikan pemahaman'])[1]/following::span[1]</value>
      <webElementGuid>c4070395-f903-44bf-9079-cff6f0d9dcf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelas 1 SD'])[2]/preceding::span[1]</value>
      <webElementGuid>37f5eaf8-1dfe-41c2-b3e2-fa93f22ef3c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelas 2 SD'])[2]/preceding::span[1]</value>
      <webElementGuid>10435f6c-4495-4422-8b32-8b4a495807a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='×']/parent::*</value>
      <webElementGuid>f62c957e-43be-431d-b371-235ea75b1d3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span</value>
      <webElementGuid>514b6e8d-b062-4451-ba58-069f94fc8738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'gradeNonSDCloseModal' and (text() = '×' or . = '×')]</value>
      <webElementGuid>608909f5-00ff-4c89-907e-267956d6d26f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
