<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Program</name>
   <tag></tag>
   <elementGuidId>70dbeb93-832a-40f2-911f-14aa8739992f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#program > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='program']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d3ac2af3-42d8-4906-94e0-106f60d4d0b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking-event-type</name>
      <type>Main</type>
      <value>landing_page__core__item_click</value>
      <webElementGuid>8bd19649-19ae-451e-98a1-c15762bfa767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking-context</name>
      <type>Main</type>
      <value>{&quot;product_name&quot;: &quot;ruangguru&quot;,&quot;cta_action&quot;: &quot;redirection&quot;,&quot;cta_action_detail&quot;: &quot;https://www.ruangguru.com/program&quot;,&quot;item_type&quot;: &quot;link&quot;,&quot;item_name&quot;: &quot;Program&quot;,&quot;item_category&quot;: &quot;cta&quot;,&quot;item_position&quot;: 2,&quot;item_serial&quot;: null,&quot;section_type&quot;: &quot;navbar&quot;,&quot;section_position&quot;: &quot;header&quot;,&quot;section_name&quot;: &quot;header_navbar&quot;}</value>
      <webElementGuid>9b9796ef-2083-448a-9394-3f70ce267c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.ruangguru.com/program</value>
      <webElementGuid>0a2238b1-e40c-42a6-80b7-5320c61b54ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Program</value>
      <webElementGuid>e07e4b2e-dd63-4bfb-92a3-51902b723e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;program&quot;)/a[1]</value>
      <webElementGuid>bc9ee944-4398-4bf5-a058-9bdb53590c44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='program']/a</value>
      <webElementGuid>80810776-bd56-4a3b-ba2a-56074777c5fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Program')]</value>
      <webElementGuid>7ec58a30-c75c-40c8-b267-251ce7f5e29d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promo'])[1]/preceding::a[1]</value>
      <webElementGuid>0a39ec5e-420a-43c1-bd69-7eb0eaa47b08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event'])[1]/preceding::a[2]</value>
      <webElementGuid>f088443a-e88b-4917-abc2-ad9fd0f4da8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Program']/parent::*</value>
      <webElementGuid>13dc0f4d-f246-473b-8013-f7c3b4b5230b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.ruangguru.com/program')]</value>
      <webElementGuid>567c3ffa-1249-4ff4-a48b-92bc0bb31974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>775f32b7-1fcd-4084-902a-e0ffbec08101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.ruangguru.com/program' and (text() = 'Program' or . = 'Program')]</value>
      <webElementGuid>3f5f5528-037a-4ab2-bf91-9e92f2887de2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
