<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Produk</name>
   <tag></tag>
   <elementGuidId>b65a7024-acaa-48d4-93eb-03da4ec97382</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#produk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='produk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ebde87d3-5bbc-43a0-8ffc-3ba5e2c59ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navig-link navig-link-dropdown</value>
      <webElementGuid>65ecaf9c-ecf9-441a-a39a-3f7abd8e37a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>produk</value>
      <webElementGuid>c890a9ed-2e7f-4202-a07c-ec8fd3a07ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cce74527-7512-4e5c-96a2-7517bbabfe79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Produk
                </value>
      <webElementGuid>aaabd7b2-db5a-45c6-843a-acfbf62107fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;produk&quot;)</value>
      <webElementGuid>90f4896b-38b4-463e-8aa4-f19ec2e0e95a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='produk']</value>
      <webElementGuid>a5b0aa8a-b01e-4cc2-9689-42a4a620630d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='rg-header']/div/div/div[2]/div</value>
      <webElementGuid>bf17f551-86e6-497a-a5df-6d55881052bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Program'])[1]/preceding::div[28]</value>
      <webElementGuid>6a3b2389-09b1-4d07-b378-cc8bb30cdf4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promo'])[1]/preceding::div[29]</value>
      <webElementGuid>cd317ac8-aad2-41e7-9cc6-0e2f95efdcc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div</value>
      <webElementGuid>895d1ef8-3e7f-4de1-ac74-294377d0913a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'produk' and (text() = '
                    Produk
                ' or . = '
                    Produk
                ')]</value>
      <webElementGuid>f0f17b49-6131-41c9-a60e-45a883e9c816</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
