<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Program</name>
   <tag></tag>
   <elementGuidId>d4e0c68f-9630-4ca4-9527-0885551d82c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#program > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='program']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d0401b8f-9270-441f-8120-d8f3f62ae4d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking-event-type</name>
      <type>Main</type>
      <value>landing_page__core__item_click</value>
      <webElementGuid>7b14e40f-24ff-4a14-b1a5-71c504a8e3a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking-context</name>
      <type>Main</type>
      <value>{&quot;product_name&quot;: &quot;ruangguru&quot;,&quot;cta_action&quot;: &quot;redirection&quot;,&quot;cta_action_detail&quot;: &quot;https://www.ruangguru.com/program&quot;,&quot;item_type&quot;: &quot;link&quot;,&quot;item_name&quot;: &quot;Program&quot;,&quot;item_category&quot;: &quot;cta&quot;,&quot;item_position&quot;: 2,&quot;item_serial&quot;: null,&quot;section_type&quot;: &quot;navbar&quot;,&quot;section_position&quot;: &quot;header&quot;,&quot;section_name&quot;: &quot;header_navbar&quot;}</value>
      <webElementGuid>6f7f23b4-94cb-49ff-ad51-feb08d3fb359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.ruangguru.com/program</value>
      <webElementGuid>c617a262-cea6-4717-b961-a256f59a3832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Program</value>
      <webElementGuid>130d1bc2-959e-4098-bade-8a8d81feaab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;program&quot;)/a[1]</value>
      <webElementGuid>c9609377-75e6-4a50-b505-32687a861174</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='program']/a</value>
      <webElementGuid>27ba9581-c375-4bc4-823b-6e5eee187507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Program')]</value>
      <webElementGuid>ee9f6a73-7257-4ec8-b89f-2fd4d042dbca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promo'])[1]/preceding::a[1]</value>
      <webElementGuid>b8186306-c7aa-4606-b0e5-7eaef69a3b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event'])[1]/preceding::a[2]</value>
      <webElementGuid>6a1e2a55-3f9f-4652-895a-2ad312598275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Program']/parent::*</value>
      <webElementGuid>e9b0612b-8e25-4dfa-886a-4ae6d9a35b75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.ruangguru.com/program')]</value>
      <webElementGuid>9a1effb9-160b-4174-bd6e-f14bf043c6e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>687fef39-ffd5-4ad3-8c10-f65cda982068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.ruangguru.com/program' and (text() = 'Program' or . = 'Program')]</value>
      <webElementGuid>c368491c-523e-4dda-983d-126801b2abf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
