<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>18f1b865-6618-42d6-963b-39b79d170741</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.close-jenjang</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jenjangModal']/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0fa85a8f-a519-4ff9-943f-972bf21e740b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking-event-type</name>
      <type>Main</type>
      <value>landing_page__core__item_click</value>
      <webElementGuid>f91f6b9e-3ba3-4c10-8ac9-6837edf9b290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking-context</name>
      <type>Main</type>
      <value>{&quot;product_name&quot;: &quot;ruangguru&quot;,&quot;cta_action&quot;: &quot;close&quot;,&quot;cta_action_detail&quot;: &quot;close_popup_grade_selection&quot;,&quot;item_type&quot;: &quot;button&quot;,&quot;item_name&quot;: &quot;Close&quot;,&quot;item_category&quot;: &quot;cta&quot;,&quot;item_position&quot;: 0,&quot;item_serial&quot;: null,&quot;section_type&quot;: &quot;popup&quot;,&quot;section_position&quot;: &quot;body&quot;,&quot;section_name&quot;: &quot;popup_grade_selection&quot;}</value>
      <webElementGuid>556b6573-f261-4b0a-ab9c-e44c584d765b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close-jenjang</value>
      <webElementGuid>0faa89f3-fea9-4dcb-9cc9-691db1dee087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>a82c57ce-3e1b-47c5-bade-24d760e6d315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jenjangModal&quot;)/div[@class=&quot;modal-content-jenjang&quot;]/div[@class=&quot;modal-body-jenjang&quot;]/span[@class=&quot;close-jenjang&quot;]</value>
      <webElementGuid>6d1abcbd-77c8-44f0-9708-b35459f52f0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jenjangModal']/div/div/span</value>
      <webElementGuid>ff2d6959-382f-499f-a476-1980778bf247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- Kelas 12 IPA'])[1]/following::span[1]</value>
      <webElementGuid>31a10e0b-2328-4578-b4d8-f31f7bedce79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SMA'])[2]/following::span[2]</value>
      <webElementGuid>c5ecf153-3677-4381-9e74-17b5a61cd244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAUD'])[2]/preceding::span[1]</value>
      <webElementGuid>42cfc317-790f-4bc8-9f7a-ebdb05fdcadd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SD'])[2]/preceding::span[1]</value>
      <webElementGuid>566c53e5-f318-49cd-b643-c825ca063812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/span</value>
      <webElementGuid>55df5ad6-2569-4265-b872-a0d8d46a3975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '×' or . = '×')]</value>
      <webElementGuid>9a3da009-c8ad-4b71-b65e-991258731f5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
