<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>5135eda6-b3dc-478f-96a4-6c1f89fc6f72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='section-cara-pembelian']/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1be2a014-2909-445f-8400-6086283ce712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.ruangguru.com/hubfs/RG%20Cara%20Bayar/ic_chevrondown_s.png</value>
      <webElementGuid>397d6b1a-ff6d-475c-924c-7bb02e962653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Aset</value>
      <webElementGuid>bfe1fd59-3e37-4862-b043-deff7af246cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section-cara-pembelian&quot;)/div[@class=&quot;page-center&quot;]/div[@class=&quot;cp-content&quot;]/div[@class=&quot;cp-item-list&quot;]/div[@class=&quot;snk__content&quot;]/div[@class=&quot;faq-content_accordion&quot;]/div[@class=&quot;accordion-faq&quot;]/div[@class=&quot;container-acc2&quot;]/div[@class=&quot;accordion2&quot;]/div[@class=&quot;accordion-subject&quot;]/div[@class=&quot;accordion-img&quot;]/img[1]</value>
      <webElementGuid>df18ffb0-60cf-4438-b344-44185ae22e26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='section-cara-pembelian']/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/img</value>
      <webElementGuid>a085af0a-4391-4a7c-9c90-ad597be78cff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Aset'])[2]</value>
      <webElementGuid>20f38e1f-b31e-4549-a890-9e325ca8722d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/img</value>
      <webElementGuid>f08a5eee-5cc9-4ea5-a4fa-886a03b37a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.ruangguru.com/hubfs/RG%20Cara%20Bayar/ic_chevrondown_s.png' and @alt = 'Aset']</value>
      <webElementGuid>e10d7973-0b0f-4d35-9dcd-5a9c0d478d4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='section-cara-pembelian']/div/div/div[2]/div[2]/div/div/div/div/div/div[2]/img</value>
      <webElementGuid>ae0760a1-6fda-45c4-903b-3ed3d30e978a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Aset']</value>
      <webElementGuid>05c9c8b0-21c0-4814-9024-69f3e3877796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[2]/img</value>
      <webElementGuid>1ece0f0a-929d-407e-bf02-ec30fbd62a58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
