<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Kurikulum Merdeka</name>
   <tag></tag>
   <elementGuidId>3bd299b2-c883-4f15-86cb-b19ba8a74853</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chakra-modal--body-2']/div[2]/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>499db66c-b9c7-47bf-9cdb-4e6ec8a4ad0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-6khw3y</value>
      <webElementGuid>e67925f5-83f7-488e-a39b-ed52b67a89eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kurikulum Merdeka</value>
      <webElementGuid>bd74b03c-33de-47db-a105-554cedec6a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal--body-2&quot;)/div[@class=&quot;chakra-stack css-1cbeopk&quot;]/div[@class=&quot;css-6khw3y&quot;]</value>
      <webElementGuid>74d050c4-e15c-4c62-9594-12e244bd2fbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-2']/div[2]/div[3]</value>
      <webElementGuid>ca3c8308-65fb-41c3-969f-3db4f901fa71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IPS - K13 Revisi'])[1]/following::div[1]</value>
      <webElementGuid>0f3603d3-b73a-4f9d-9dfe-52968659b373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IPA - K13 Revisi'])[1]/following::div[2]</value>
      <webElementGuid>96a7f0ae-d09f-477e-b817-4dfaf15428f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[1]/preceding::div[1]</value>
      <webElementGuid>31926cf5-fef3-4ac7-baea-fb2cc281ce87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kurikulum Merdeka']/parent::*</value>
      <webElementGuid>8f251b7f-2762-4ca1-b4d9-9f092a3666b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div[2]/div[3]</value>
      <webElementGuid>990e4c62-ec62-4920-9d8f-f7354c09a5c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Kurikulum Merdeka' or . = 'Kurikulum Merdeka')]</value>
      <webElementGuid>f57cdf8b-4e15-42b0-8caa-f15971fd0a0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
