<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__css-qnu5bt</name>
   <tag></tag>
   <elementGuidId>0565645a-bb0d-429b-9f3f-b1567f3fb921</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-root']/div/div/div/div/div[2]/div/div/div[2]/div/div[2]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-qnu5bt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6430c7ef-2daf-4e2e-854b-fd7c83f2d14c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-qnu5bt</value>
      <webElementGuid>5813f721-da2d-4867-bdc0-b8c2b31653d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-root&quot;)/div[1]/div[@class=&quot;css-15fvfn7&quot;]/div[@class=&quot;css-eele9v&quot;]/div[@class=&quot;css-1wkd45b&quot;]/div[@class=&quot;css-sz9opq&quot;]/div[@class=&quot;css-l5u1lg&quot;]/div[@class=&quot;css-o6yovt&quot;]/div[@class=&quot;css-1rmhad2&quot;]/div[@class=&quot;css-1xm006u&quot;]/div[@class=&quot;css-2sbipq&quot;]/div[@class=&quot;css-1tc80em&quot;]/div[@class=&quot;css-1bn9zv9&quot;]/div[@class=&quot;css-qnu5bt&quot;]</value>
      <webElementGuid>1a0faf21-e3e0-43eb-a912-8ed3a13f3371</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-root']/div/div/div/div/div[2]/div/div/div[2]/div/div[2]/div/div/div</value>
      <webElementGuid>557c5375-97ce-4819-a8ca-b1e1ae88db9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div</value>
      <webElementGuid>75c88744-121c-4a83-a2ab-85f87db96e54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
