<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Simpan</name>
   <tag></tag>
   <elementGuidId>61bacc88-0ac8-4a6f-b578-231e66d94874</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='select-filter-button']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-1q3ffy1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>db6664d0-479c-430e-895a-e7c59df94f33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1q3ffy1</value>
      <webElementGuid>714d3920-f2a3-42d2-b739-f3ab12644b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simpan</value>
      <webElementGuid>76b92bc3-b35e-4572-b6e5-df3d71011cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-filter-button&quot;)/div[@class=&quot;css-1q3ffy1&quot;]</value>
      <webElementGuid>9657ecca-22b1-4cb6-9f9e-1cbae1231444</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='select-filter-button']/div</value>
      <webElementGuid>2d82576a-9099-42cb-b575-c4df205b5068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::div[30]</value>
      <webElementGuid>1c8a254a-02fc-4574-b6e9-f058688cbe9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'select-filter-button', '&quot;', ')/div[@class=', '&quot;', 'css-1q3ffy1', '&quot;', ']')])[1]/preceding::div[1]</value>
      <webElementGuid>073da541-913c-41f5-a49b-64cd84de8dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div[2]/div/div</value>
      <webElementGuid>f4b2637f-fac4-44d9-8c34-7a3b28c9c945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Simpan' or . = 'Simpan')]</value>
      <webElementGuid>597646d2-6ece-49ab-93a5-010bf802cfa0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
