<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Bahasa</name>
   <tag></tag>
   <elementGuidId>fdee5776-4095-481c-aff4-a64bd5462a5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='bahasa']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bahasa</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9ee26b61-4f2f-4cee-a256-1a7ae9c85b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-tab</value>
      <webElementGuid>d8c1a287-6ad3-40a0-a60b-b0b2d8e27a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bahasa</value>
      <webElementGuid>1a3009e0-aa00-47cd-802d-2d936d1f1898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>bahasa</value>
      <webElementGuid>dd4ac6d0-2c57-4057-91a5-4da4a8f0421c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bahasa</value>
      <webElementGuid>7bc68cca-1b14-4ece-a668-f959769391e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bahasa&quot;)</value>
      <webElementGuid>f7420d37-1c64-4ab2-8428-440754e30159</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='bahasa']</value>
      <webElementGuid>51918974-27b3-4523-ba70-7a8cc4c6acc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='btnCategory']/div/button[2]</value>
      <webElementGuid>a4e1965a-447e-4b2c-ba0c-ee5c2e7a82de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Akademis'])[1]/following::button[1]</value>
      <webElementGuid>f0108474-f9d0-4ef8-9a4e-badd6a4896c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilihan Produk Ruangguru'])[1]/following::button[2]</value>
      <webElementGuid>a2ebb331-4fe8-4c91-aaa4-86953899aef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Life &amp; Future Skills'])[1]/preceding::button[1]</value>
      <webElementGuid>b21285be-8e74-480e-b30d-ba74ac6ffc7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Homeschooling'])[1]/preceding::button[2]</value>
      <webElementGuid>a96213c1-9015-4169-af9f-63ec699079af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bahasa']/parent::*</value>
      <webElementGuid>93933c06-9a30-456c-a418-6a824f6dc207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>341e0f46-51dd-46ef-bb65-c1f370288a03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'bahasa' and (text() = 'Bahasa' or . = 'Bahasa')]</value>
      <webElementGuid>b5cfe347-85ea-4871-aee7-b147c239bd06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
