<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Selengkapnya</name>
   <tag></tag>
   <elementGuidId>2f4dd662-9852-4942-b68e-0e3ccf6f2956</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='seeMore-75766375506']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#seeMore-75766375506</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3a726fba-3959-4fcf-bcb9-bc6f25c9bb49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-see-more</value>
      <webElementGuid>18c79ce7-9533-4236-8a1a-63c8f469f115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>seeMore-75766375506</value>
      <webElementGuid>25220753-f91e-44c0-b13a-347a514a9542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selengkapnya </value>
      <webElementGuid>0f4213ec-ecbd-4420-a6ac-4b85a151cec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;seeMore-75766375506&quot;)</value>
      <webElementGuid>b854a767-10d7-428e-a3fc-c0dfd2d90b63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='seeMore-75766375506']</value>
      <webElementGuid>eabac4a2-2ea3-4aa5-ad5d-e30e0c1bbe3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pointsProduct-75766375506']/div/span</value>
      <webElementGuid>7845ac08-c345-4f9e-b368-c70d6f79ae81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporan perkembangan belajar bulanan dan sertifikat per level'])[1]/following::span[1]</value>
      <webElementGuid>c49ba3ba-69d1-4177-a64a-fa71b277bab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gratis buku belajar setiap level'])[1]/following::span[1]</value>
      <webElementGuid>47f7e2a6-6f93-406f-a0f5-896f5e3d9dad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coba Kelas Gratis!'])[2]/preceding::span[1]</value>
      <webElementGuid>e74dca0a-aa05-45b0-a770-9b65f345e699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Program'])[3]/preceding::span[3]</value>
      <webElementGuid>420539e1-4dab-483f-bc3c-04f9056949c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/span</value>
      <webElementGuid>ef242ed8-f6a3-493c-b056-83ffb0efeeb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'seeMore-75766375506' and (text() = 'Selengkapnya ' or . = 'Selengkapnya ')]</value>
      <webElementGuid>3153f452-4efd-476b-abd4-9683679313f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
