<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PAUD</name>
   <tag></tag>
   <elementGuidId>3dea9741-fac7-47c0-a923-2f29a61e3f89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-bmnq0u</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chakra-modal--body-14']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5d284ce1-651b-4876-8d68-59a991750147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-bmnq0u</value>
      <webElementGuid>0bcdfc2e-ca8f-49e2-ba86-2490e3aa1305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PAUD</value>
      <webElementGuid>876cf904-5b88-4730-9a64-ba8add1fb1bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal-14&quot;)/div[@id=&quot;chakra-modal--body-14&quot;]/div[@class=&quot;css-u55dt8&quot;]/div[@class=&quot;css-bmnq0u&quot;]</value>
      <webElementGuid>e749ace9-31c6-44bd-8044-e0b9e7273eb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-14']/div/div</value>
      <webElementGuid>14eb40f4-b9c7-4f82-a067-452e46f52a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data produk tidak ditemukan, coba pilih kelas lain.'])[1]/following::div[13]</value>
      <webElementGuid>0870edd9-f9f5-4926-8dcb-7f8fc365d143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk / Daftar'])[1]/following::div[52]</value>
      <webElementGuid>63010723-603d-48d3-8836-4f4e898c47e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[1]/preceding::div[8]</value>
      <webElementGuid>9f243690-b654-4d67-bf4b-6a4bb0a13e97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div</value>
      <webElementGuid>25ad0fcf-6a23-4cf6-9524-55a8ca8005a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'PAUD' or . = 'PAUD')]</value>
      <webElementGuid>fe8c8840-3a8f-450c-9ce4-a816f750aa5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
