<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_4 Tahun</name>
   <tag></tag>
   <elementGuidId>975c562a-527e-4438-bb19-bbff89f335f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-em0uk8 > div.css-bmnq0u</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='chakra-modal--body-14']/div/div)[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b6392d4d-d2e3-42ea-84d0-a28a3e947052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-bmnq0u</value>
      <webElementGuid>c3481f4d-7558-48dd-a9e9-debcf40d70fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4 Tahun</value>
      <webElementGuid>76c99023-4713-4d73-8777-41e3800d4148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal-14&quot;)/div[@id=&quot;chakra-modal--body-14&quot;]/div[@class=&quot;css-em0uk8&quot;]/div[@class=&quot;css-bmnq0u&quot;]</value>
      <webElementGuid>f25a0c3b-2d84-4413-8cbc-7e9fb48045be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='chakra-modal--body-14']/div/div)[7]</value>
      <webElementGuid>060569ed-57cf-4e8c-afa0-ca75dc6c5ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data produk tidak ditemukan, coba pilih kelas lain.'])[1]/following::div[21]</value>
      <webElementGuid>a74361a9-a698-4bfe-8cb6-eacddd74104e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk / Daftar'])[1]/following::div[60]</value>
      <webElementGuid>ddbd70c1-f26e-4c18-aa2c-e3b4fba54ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[1]/preceding::div[5]</value>
      <webElementGuid>4e4eac0d-5b7a-497d-a330-5bfb83cf0e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[2]/div/div</value>
      <webElementGuid>f3584a0c-05bf-4495-9c4a-0c362af016a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '4 Tahun' or . = '4 Tahun')]</value>
      <webElementGuid>1faf314c-aa04-48bb-8113-b290cbd5176a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
