<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__firstname</name>
   <tag></tag>
   <elementGuidId>6a8ac3c5-279a-49c5-a1ef-bd69506c0249</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='firstname-07ec13ea-342b-46c1-8ea0-44bc333c5190']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#firstname-07ec13ea-342b-46c1-8ea0-44bc333c5190</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e919480-ff2a-42c6-abbe-40624c237f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>firstname-07ec13ea-342b-46c1-8ea0-44bc333c5190</value>
      <webElementGuid>95ca1780-aafc-48d0-901b-8c46d4c03123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>firstname</value>
      <webElementGuid>1aa830c2-fa51-452e-8589-7f45a9c1ec5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama lengkap orang tua</value>
      <webElementGuid>284f6bdf-db2f-4bdb-8792-42f55935cf91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>53e2d237-f5ed-438c-9b86-7f69b09680a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hs-input</value>
      <webElementGuid>6b00167d-5bce-441f-a735-3959077855a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f8754551-176c-4178-bfa8-0f1a61ebdaf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>given-name</value>
      <webElementGuid>9348d284-4fda-4319-b64b-6f8c59c802e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;firstname-07ec13ea-342b-46c1-8ea0-44bc333c5190&quot;)</value>
      <webElementGuid>64b58d7b-ee82-49be-ac49-7d64e6df47fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='firstname-07ec13ea-342b-46c1-8ea0-44bc333c5190']</value>
      <webElementGuid>73244995-7d2e-42fd-be99-fb0d9e0b51d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='hsForm_07ec13ea-342b-46c1-8ea0-44bc333c5190']/div[2]/div/input</value>
      <webElementGuid>a61c63b7-0a65-45ca-b028-e69116de2844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>85a5be01-4e7c-4533-b41a-a86511f1fa34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'firstname-07ec13ea-342b-46c1-8ea0-44bc333c5190' and @name = 'firstname' and @placeholder = 'Nama lengkap orang tua' and @type = 'text']</value>
      <webElementGuid>72576784-d0a4-45f5-986f-fd8f5f097c67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
