<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__email</name>
   <tag></tag>
   <elementGuidId>dc7f5d40-2cf0-467b-b052-c793006f0d7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='email-07ec13ea-342b-46c1-8ea0-44bc333c5190']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#email-07ec13ea-342b-46c1-8ea0-44bc333c5190</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>417d2f49-48ad-4b0a-baae-b746b80b9547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email-07ec13ea-342b-46c1-8ea0-44bc333c5190</value>
      <webElementGuid>32d24b7f-1e24-402d-9449-f23e52373d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>6b892efa-54a7-41bf-9a26-23765af9257d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email Anda</value>
      <webElementGuid>754ac29e-e7c5-4adf-9662-23cebef72c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>47aea7ec-6e61-4b87-97c7-c42516421af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hs-input</value>
      <webElementGuid>884b850e-41da-41f6-b10c-5fc46117772a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>8ef37307-a782-4987-9939-587b5daaaaa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>5d32d042-fe4d-4fd0-8cf9-fa8ffe0e79fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email-07ec13ea-342b-46c1-8ea0-44bc333c5190&quot;)</value>
      <webElementGuid>57abc386-42d3-4962-b4a4-0770b24a6832</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='email-07ec13ea-342b-46c1-8ea0-44bc333c5190']</value>
      <webElementGuid>4bbb3217-fc8e-4e60-832f-a43ac88d32b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='hsForm_07ec13ea-342b-46c1-8ea0-44bc333c5190']/div[3]/div/input</value>
      <webElementGuid>b35cc2db-f019-4943-aed6-53f56ed5cc95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>8305abf7-7058-4518-a3f6-a0d5255cd34a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'email-07ec13ea-342b-46c1-8ea0-44bc333c5190' and @name = 'email' and @placeholder = 'Email Anda' and @type = 'email']</value>
      <webElementGuid>6b6bb914-603f-4459-b930-4f7cf2483454</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
