<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__asal_kota</name>
   <tag></tag>
   <elementGuidId>69763933-f8b2-4ae5-abcf-a5946e710c0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='asal_kota-07ec13ea-342b-46c1-8ea0-44bc333c5190']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#asal_kota-07ec13ea-342b-46c1-8ea0-44bc333c5190</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b03e5ce2-1ec2-48ed-9eb3-c06859911dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>asal_kota-07ec13ea-342b-46c1-8ea0-44bc333c5190</value>
      <webElementGuid>ab013fe4-d933-4b96-801b-ba2cc7be9652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asal_kota</value>
      <webElementGuid>38f2ae0b-a1d5-465d-819a-bad47251e8c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: Jakarta Barat </value>
      <webElementGuid>2a2f3f4f-726d-43ff-8af9-4041ec5bb3a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>08208f73-61b4-4726-b481-40290589afc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hs-input</value>
      <webElementGuid>480034a0-9b31-4a8b-b6ab-c9a2d891a828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8ccf2f65-120b-457f-80cd-5265be654b85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;asal_kota-07ec13ea-342b-46c1-8ea0-44bc333c5190&quot;)</value>
      <webElementGuid>8ff66fc8-5b4b-4a11-8c61-5e7b65390ed0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='asal_kota-07ec13ea-342b-46c1-8ea0-44bc333c5190']</value>
      <webElementGuid>3d13c848-3d1b-4ed5-8ded-dee705972d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='hsForm_07ec13ea-342b-46c1-8ea0-44bc333c5190']/div[5]/div/input</value>
      <webElementGuid>12fd91d6-ff56-401e-b70d-13f8d7359606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>a0ab33c2-1ea3-4f76-8515-37ad0cbd5893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'asal_kota-07ec13ea-342b-46c1-8ea0-44bc333c5190' and @name = 'asal_kota' and @placeholder = 'Contoh: Jakarta Barat ' and @type = 'text']</value>
      <webElementGuid>edd7517f-e6d1-4de4-8433-1ceda1522b8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
