<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__student_name</name>
   <tag></tag>
   <elementGuidId>4c6d3f8d-0b1c-4bc8-88b2-57d24374a778</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='student_name-07ec13ea-342b-46c1-8ea0-44bc333c5190']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#student_name-07ec13ea-342b-46c1-8ea0-44bc333c5190</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>05c20a21-65e5-4224-a5e6-be60621639e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>student_name-07ec13ea-342b-46c1-8ea0-44bc333c5190</value>
      <webElementGuid>eb58cf55-5990-4d70-b1ab-da322ca61c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>student_name</value>
      <webElementGuid>c5210dda-ee2c-4cb2-8488-a38391742eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Isi nama lengkap anak Anda</value>
      <webElementGuid>777afb70-d97e-4db6-9f33-976ada3af0b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a3a4a5a4-a5b4-4af6-a753-d0ef408a17b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hs-input</value>
      <webElementGuid>1981bcc8-2231-405a-9abd-35963d238889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>54dd8858-3c95-4400-8f14-f1f19fc94d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;student_name-07ec13ea-342b-46c1-8ea0-44bc333c5190&quot;)</value>
      <webElementGuid>2881b13b-fe24-44ae-be61-f606536569fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='student_name-07ec13ea-342b-46c1-8ea0-44bc333c5190']</value>
      <webElementGuid>3a9befed-fb9c-4475-a2e3-b43687c6eeb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='hsForm_07ec13ea-342b-46c1-8ea0-44bc333c5190']/div[6]/div/input</value>
      <webElementGuid>79bed4b5-bab0-4411-9d11-ec1c929f9f5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>9d373d6f-e911-4e84-9a05-4b73e4b891ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'student_name-07ec13ea-342b-46c1-8ea0-44bc333c5190' and @name = 'student_name' and @placeholder = 'Isi nama lengkap anak Anda' and @type = 'text']</value>
      <webElementGuid>18d27afe-5036-4a54-8e73-f2272c39fa84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
