<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_PilihCalistung Matematika  Bahasa In_cd6aa7</name>
   <tag></tag>
   <elementGuidId>90dde6cc-f8c5-4dc5-adb5-d0e6f52e1283</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='pilih_program_kursus-07ec13ea-342b-46c1-8ea0-44bc333c5190']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pilih_program_kursus-07ec13ea-342b-46c1-8ea0-44bc333c5190</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2443f3a3-76d0-4e12-8413-6a5762eaaf04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pilih_program_kursus-07ec13ea-342b-46c1-8ea0-44bc333c5190</value>
      <webElementGuid>cd50afde-ff93-4176-acce-206944eb007c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hs-input is-placeholder</value>
      <webElementGuid>fd998560-4f81-4cde-8acf-2149b35095d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pilih_program_kursus</value>
      <webElementGuid>1e79d321-0d44-427f-910a-86b9640f9141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PilihCalistung Matematika &amp; Bahasa InggrisScience, Math, &amp; English</value>
      <webElementGuid>57c11ac7-67a1-45ee-989f-799ba4773201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pilih_program_kursus-07ec13ea-342b-46c1-8ea0-44bc333c5190&quot;)</value>
      <webElementGuid>d6a10ae4-c433-4c1f-b2c2-a554cff70b23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='pilih_program_kursus-07ec13ea-342b-46c1-8ea0-44bc333c5190']</value>
      <webElementGuid>81e599dd-6563-4f82-b843-093cb9b020d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='hsForm_07ec13ea-342b-46c1-8ea0-44bc333c5190']/div[8]/div/div/select</value>
      <webElementGuid>e38f8f51-de9e-463b-b30c-1954acb3df9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::select[1]</value>
      <webElementGuid>99ccd4f9-3074-4082-998b-5e462356dfb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Program Kursus'])[1]/following::select[1]</value>
      <webElementGuid>1e1cf51d-a4c5-482d-98ee-b3a7e0ebbe27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roboguru'])[1]/preceding::select[1]</value>
      <webElementGuid>e15ad501-d760-4f1b-88ba-b84cb2e78bd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roboguru Plus'])[1]/preceding::select[1]</value>
      <webElementGuid>05cef72f-7bbb-47ab-b136-4a2d7f4e44bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/select</value>
      <webElementGuid>8d732ecf-e264-43d8-a13b-48c0b92bd682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'pilih_program_kursus-07ec13ea-342b-46c1-8ea0-44bc333c5190' and @name = 'pilih_program_kursus' and (text() = 'PilihCalistung Matematika &amp; Bahasa InggrisScience, Math, &amp; English' or . = 'PilihCalistung Matematika &amp; Bahasa InggrisScience, Math, &amp; English')]</value>
      <webElementGuid>ec5ed66d-60ab-4847-a327-64d9d5389b24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
