<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_PilihONLINE Kamis, 27 April, Jam 14._2e5f52</name>
   <tag></tag>
   <elementGuidId>3b69549d-d9a8-4655-a0e8-65845364abdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='alta_program_jadwal_matheng-07ec13ea-342b-46c1-8ea0-44bc333c5190']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#alta_program_jadwal_matheng-07ec13ea-342b-46c1-8ea0-44bc333c5190</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5946554e-ddbe-471b-be99-bdb53db6431c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alta_program_jadwal_matheng-07ec13ea-342b-46c1-8ea0-44bc333c5190</value>
      <webElementGuid>25944f5c-0905-437d-9a6a-231c3f6c6b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hs-input is-placeholder</value>
      <webElementGuid>36dc6833-5fe8-4a7e-a2f9-030e87367f00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>alta_program_jadwal_matheng</value>
      <webElementGuid>2055cdab-0fa6-424f-8ba6-04c93b4750c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih[ONLINE] Kamis, 27 April, Jam 14.15-15.15 WIB </value>
      <webElementGuid>56e03c7a-6c2e-48a8-b407-2d86ee03f325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alta_program_jadwal_matheng-07ec13ea-342b-46c1-8ea0-44bc333c5190&quot;)</value>
      <webElementGuid>d89b2957-12f3-4aae-bf66-bdd0d45451af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='alta_program_jadwal_matheng-07ec13ea-342b-46c1-8ea0-44bc333c5190']</value>
      <webElementGuid>be43832c-4dc1-4917-b320-cba8f950ab88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='hsForm_07ec13ea-342b-46c1-8ea0-44bc333c5190']/div[8]/div[2]/div/select</value>
      <webElementGuid>0aba57f8-b2bc-4ce8-b989-d5ee35800ac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/following::select[1]</value>
      <webElementGuid>bc63e9b6-ba9c-492c-a561-198dd1f122ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih tanggal dan waktu trial class'])[1]/following::select[1]</value>
      <webElementGuid>d18b4868-53b5-4f66-afae-dd24ebf93c07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roboguru'])[1]/preceding::select[1]</value>
      <webElementGuid>8656033f-84a8-4411-b921-900ad7d2a782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roboguru Plus'])[1]/preceding::select[1]</value>
      <webElementGuid>bdc3abf4-4eaa-4946-ab3a-2de7089489da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>cf072e36-8c75-4fd8-9b34-33418b6b8ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'alta_program_jadwal_matheng-07ec13ea-342b-46c1-8ea0-44bc333c5190' and @name = 'alta_program_jadwal_matheng' and (text() = 'Pilih[ONLINE] Kamis, 27 April, Jam 14.15-15.15 WIB ' or . = 'Pilih[ONLINE] Kamis, 27 April, Jam 14.15-15.15 WIB ')]</value>
      <webElementGuid>7cd99fd1-3a15-4405-9b01-93601e34aee6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
