<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Beli</name>
   <tag></tag>
   <elementGuidId>564e36a6-5e3e-4fed-937f-187b0739786b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='hero-section-course-detail']/div/div/div/div[2]/div/div/div/div[2]/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.anc.cta-c-1.d-block</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0b7c752b-d0ab-47b1-bda7-f75a62fbd9c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://bayar.ruangguru.com/npf/packages?tag=rgkids&amp;referralCookiesId=f10a6327-274e-4728-82c5-20bc8135b222</value>
      <webElementGuid>3739bf6c-b7e1-4cbf-9f85-afc9321c43a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>d7d7fdf3-ba65-421d-bf7e-2bec7172ba4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>anc cta-c-1 d-block</value>
      <webElementGuid>3f81539c-b9bc-493a-9147-f320e6cecb76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            Beli
                                        </value>
      <webElementGuid>c98564aa-659b-46ea-ae53-c1c626fadefc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hero-section-course-detail&quot;)/div[@class=&quot;row px-0 mx-0 pb-0&quot;]/div[@class=&quot;col-12 col-hero-c px-0&quot;]/div[@class=&quot;page-center&quot;]/div[@class=&quot;row row-hero-section-course-detail px-0 mx-0 py-0&quot;]/div[@class=&quot;col-12 col-xl-6 col-c-1 px-0&quot;]/div[@class=&quot;card card-hero-1 bg-transparent border-0&quot;]/div[@class=&quot;card-body px-0&quot;]/div[@class=&quot;row row-c-2 px-0 mx-0 div-cta-c&quot;]/div[@class=&quot;col-12 col-xl-6&quot;]/a[@class=&quot;anc cta-c-1 d-block&quot;]</value>
      <webElementGuid>970b5c1e-7839-430f-b28b-f05421654ccc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='hero-section-course-detail']/div/div/div/div[2]/div/div/div/div[2]/div[2]/a</value>
      <webElementGuid>0e7b5b30-f1a3-4e7f-a319-3ac9891d00b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Beli')]</value>
      <webElementGuid>09f8a8e5-640a-497f-a477-9b23dd47a4b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coba Kelas Gratis'])[1]/following::a[1]</value>
      <webElementGuid>ab7dd537-fbdc-42a0-b28f-c0bedc2d2ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ruangguru Matematika &amp; Bahasa Inggris for Kids'])[1]/following::a[2]</value>
      <webElementGuid>700a7a1d-ac77-40ae-a0d6-b5d5d051128c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ruangguru Matematika &amp; Bahasa Inggris for Kids'])[2]/preceding::a[1]</value>
      <webElementGuid>5b3c1689-9a7c-41f5-a300-b8023e791a6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Beli']/parent::*</value>
      <webElementGuid>0be60e98-bd1b-4b9c-8ac3-ddd762258280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://bayar.ruangguru.com/npf/packages?tag=rgkids&amp;referralCookiesId=f10a6327-274e-4728-82c5-20bc8135b222')]</value>
      <webElementGuid>aeef98e5-74d7-4035-9e27-eac70b68a35b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div[2]/a</value>
      <webElementGuid>6ef4175d-ead0-4e77-987a-940a8cc59347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://bayar.ruangguru.com/npf/packages?tag=rgkids&amp;referralCookiesId=f10a6327-274e-4728-82c5-20bc8135b222' and (text() = '
                                            Beli
                                        ' or . = '
                                            Beli
                                        ')]</value>
      <webElementGuid>e5f94575-0712-45d3-8041-cd1df34d91dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
