<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>f9c5999b-59e3-409f-a979-4c96189ea43e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.close-jenjang</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jenjangModal']/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8cc5bffe-6bc0-48af-b5e8-1128fc1c6b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking-event-type</name>
      <type>Main</type>
      <value>landing_page__core__item_click</value>
      <webElementGuid>2fcb2e59-19b2-4e4c-943b-9b2467b21fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking-context</name>
      <type>Main</type>
      <value>{&quot;product_name&quot;: &quot;ruangguru&quot;,&quot;cta_action&quot;: &quot;close&quot;,&quot;cta_action_detail&quot;: &quot;close_popup_grade_selection&quot;,&quot;item_type&quot;: &quot;button&quot;,&quot;item_name&quot;: &quot;Close&quot;,&quot;item_category&quot;: &quot;cta&quot;,&quot;item_position&quot;: 0,&quot;item_serial&quot;: null,&quot;section_type&quot;: &quot;popup&quot;,&quot;section_position&quot;: &quot;body&quot;,&quot;section_name&quot;: &quot;popup_grade_selection&quot;}</value>
      <webElementGuid>6be34350-f938-41ac-96e7-8976766b8539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close-jenjang</value>
      <webElementGuid>f08ecf60-d708-4c36-8414-84930b5beed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>3499875d-8203-4d5a-92fc-c04e7ef50ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jenjangModal&quot;)/div[@class=&quot;modal-content-jenjang&quot;]/div[@class=&quot;modal-body-jenjang&quot;]/span[@class=&quot;close-jenjang&quot;]</value>
      <webElementGuid>6ecc3813-dbe3-499c-891e-365dfde2fade</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jenjangModal']/div/div/span</value>
      <webElementGuid>a9a71991-15ae-46e5-a600-015e9c7ee58f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- Kelas 12 IPA'])[1]/following::span[1]</value>
      <webElementGuid>b965abb7-ba8f-4b37-9188-9bcd8da02f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SMA'])[2]/following::span[2]</value>
      <webElementGuid>cef4e04e-fc99-4553-8b27-ca3e4356f624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAUD'])[2]/preceding::span[1]</value>
      <webElementGuid>a7ebbe16-bb73-4013-a5b5-5793a7eeb690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SD'])[2]/preceding::span[1]</value>
      <webElementGuid>2a673077-85ce-4981-999e-70fb481e818e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/span</value>
      <webElementGuid>fc86a2ef-e0e7-419e-b9db-2f444046dd4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '×' or . = '×')]</value>
      <webElementGuid>d294a7cd-b109-415a-a690-c2b484dfee35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
