<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DAFTARMASUK</name>
   <tag></tag>
   <elementGuidId>4068af9c-e48c-4e83-9cc6-d79966ac4089</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-1yajx7p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div/div/div[5]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>eaa00e19-ddbe-41b6-a18d-4e9677bf028d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1yajx7p</value>
      <webElementGuid>ee97cdfe-a574-43f8-9598-68163997d37a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DAFTAR/MASUK</value>
      <webElementGuid>ec345ac1-871f-445e-a83f-f101081f3763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1vlel8&quot;]/div[@class=&quot;css-ed1os&quot;]/div[@class=&quot;css-bu0fqy&quot;]/div[@class=&quot;css-4i55s3&quot;]/div[1]/div[@class=&quot;css-18stsh5&quot;]/div[@class=&quot;css-1yajx7p&quot;]</value>
      <webElementGuid>a466fd3a-fbe5-4378-baf1-7eb379cc3e97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div/div[5]/div</value>
      <webElementGuid>93184c1c-b0a0-4de0-baf4-daf7a6e0c451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelas Prakerja'])[1]/preceding::div[638]</value>
      <webElementGuid>947c794b-144b-4684-b6e8-938f21f0e07d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Program belajar terlengkap dengan metode belajar'])[1]/preceding::div[638]</value>
      <webElementGuid>1265833c-274d-4ad9-81ce-3a1f41fb3251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div</value>
      <webElementGuid>bfd3142e-6277-45c9-a682-ddc1ac66a3e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'DAFTAR/MASUK' or . = 'DAFTAR/MASUK')]</value>
      <webElementGuid>1b4db162-f369-4347-9df1-070f711b721c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
