<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_</name>
   <tag></tag>
   <elementGuidId>e9d2118c-3ed3-42dd-a027-cad3296e0b30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.css-q7mxjq</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-root']/div/div/div/div/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>49f230fb-80ed-4093-a7ac-c7d211857791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-q7mxjq</value>
      <webElementGuid>373d7349-f10c-4d59-b57d-e28e70412daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+</value>
      <webElementGuid>e9c324f2-efc9-419d-9a28-f9f05789b0b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-root&quot;)/div[1]/div[@class=&quot;css-wh8vrs&quot;]/div[@class=&quot;css-oprbr7&quot;]/div[@class=&quot;css-1o4axai&quot;]/div[@class=&quot;css-15wy7rm&quot;]/div[@class=&quot;css-19dy3j4&quot;]/p[@class=&quot;css-q7mxjq&quot;]</value>
      <webElementGuid>1c7a0c11-ab8f-429c-8329-3a40ecb7e45b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-root']/div/div/div/div/div/div/p</value>
      <webElementGuid>5c108d3f-63cd-4a25-a40b-0f2cb1431913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belajar Merancang Produk Digital untuk Manajer Pengembangan Aplikasi TIK (Product Manager)'])[2]/following::p[36]</value>
      <webElementGuid>21227d95-74a6-490e-b827-c7e203661054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kuasai Teknik Storytelling &amp; Creative Writing untuk Non-Fiksi'])[1]/following::p[45]</value>
      <webElementGuid>c00e4600-668d-4370-b4d8-b04f6feee7ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='+']/parent::*</value>
      <webElementGuid>50832859-3bdb-4dac-a3d5-57903d154ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/p</value>
      <webElementGuid>5e3b6541-db1a-4ab3-a014-aed20658368a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '+' or . = '+')]</value>
      <webElementGuid>404e7406-958c-4d89-aed4-a1a9631ccc40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
