<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Energi Listrik dan Daya Listrik_c-kdNqlf</name>
   <tag></tag>
   <elementGuidId>292b63b8-74fb-479f-b1e7-ca4de8f1972a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Energi Listrik dan Daya Listrik'])[1]/following::*[name()='svg'][40]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.c-lesPJm.c-lesPJm-ifTDhVJ-css > svg.c-kdNqlf</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>98a7f478-015b-400c-a9b0-0ac15a4679de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>f12f2877-077e-4ad7-97d3-9fa568511b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>6f860046-ae8c-4020-89c6-53eafa92433a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 15 15</value>
      <webElementGuid>645e5981-ebc7-4ea8-8a60-b7242bcfb372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>b1d9e32c-9c15-4632-8d6d-09b400dbe640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>313637fb-4292-417b-940e-731daf99ecce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-kdNqlf</value>
      <webElementGuid>5bbc956a-118d-4794-b182-7cccf33e4c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;video-content-container&quot;)/div[@class=&quot;css-1dvyg0k&quot;]/div[@class=&quot;c-lesPJm&quot;]/div[@class=&quot;c-dhzjXW c-dhzjXW-icJJpPV-css&quot;]/div[@class=&quot;c-dhzjXW c-dhzjXW-iezhUtL-css&quot;]/div[@class=&quot;c-dhzjXW c-dhzjXW-ibBIbDJ-css&quot;]/div[@class=&quot;c-lesPJm c-lesPJm-ifTDhVJ-css&quot;]/svg[@class=&quot;c-kdNqlf&quot;]</value>
      <webElementGuid>202cfa8a-a4ac-4435-9016-a72d02d93176</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Energi Listrik dan Daya Listrik'])[1]/following::*[name()='svg'][40]</value>
      <webElementGuid>81233121-77b0-40ea-9086-6da5d846409c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tegangan dan Hambatan Dalam pada Baterai'])[1]/following::*[name()='svg'][46]</value>
      <webElementGuid>4bb74d18-21d2-47d0-85ed-3f39074b2d38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fullscreen'])[1]/preceding::*[name()='svg'][4]</value>
      <webElementGuid>939879e1-ea38-4348-a414-042a1af1f66e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto'])[1]/preceding::*[name()='svg'][5]</value>
      <webElementGuid>e08aafb6-456d-40d1-823b-f141ab7b2fc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
