<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Beli</name>
   <tag></tag>
   <elementGuidId>dbc9ece3-e0bb-4c74-9994-6d12d790ed4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.chakra-button.css-r4oy1x</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1b0d7c9e-3585-4328-9c73-334b3e14557d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6f71cbfe-fc95-44b2-92d6-109d155ae364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button css-r4oy1x</value>
      <webElementGuid>a72a4fdb-6b31-4bd6-877b-21e73a676f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Beli</value>
      <webElementGuid>f5c6730a-749b-4fa0-b3f6-62dcf3a34e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1xmo2e7&quot;]/div[@class=&quot;css-uiz9ma&quot;]/div[@class=&quot;css-r76dwp&quot;]/div[@class=&quot;chakra-container css-1x8cy4t&quot;]/div[@class=&quot;css-q45nvu&quot;]/div[@class=&quot;css-104q6kq&quot;]/div[@class=&quot;css-5o0w45&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-x96me0&quot;]/button[@class=&quot;chakra-button css-r4oy1x&quot;]</value>
      <webElementGuid>c9511a46-50bf-44f0-b32a-e49944bd5270</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>138afa91-c438-4440-9e5a-82dd4c2e031b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div[2]/button</value>
      <webElementGuid>fd529e81-07d4-4a6f-a862-539f3e5f5c0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pembayaran lunas'])[1]/following::button[1]</value>
      <webElementGuid>eb5dd0e5-1f90-4a3c-85d5-2128b790d3f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diskon 50%'])[3]/following::button[2]</value>
      <webElementGuid>c5d94669-537f-4a8b-8609-2dd497798cb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Syarat dan Ketentuan'])[1]/preceding::button[1]</value>
      <webElementGuid>dace8625-05a5-45dd-8af5-4a9f8a8ada5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Syarat dan Ketentuan'])[2]/preceding::button[1]</value>
      <webElementGuid>64d33f1f-b6a1-4255-882b-f3d9e65f5371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Beli']/parent::*</value>
      <webElementGuid>4b08fac1-3d45-4014-ad0f-8a764d5dfa5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/button</value>
      <webElementGuid>71ca606c-0811-4f8a-a44e-f5f3d086573e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Beli' or . = 'Beli')]</value>
      <webElementGuid>f2c15f64-9c85-4607-874c-0dd9dcb1c6ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
