<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Email tidak valid</name>
   <tag></tag>
   <elementGuidId>85681ce8-d841-4493-ba90-5821b246fafd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-19rpcnq</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chakra-modal--body-179']/div/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2a77499f-a3cb-48af-99ea-62fcc4c14314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-19rpcnq</value>
      <webElementGuid>b8602ed0-7e9f-4595-8cf3-fa48d1b0f9d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email tidak valid</value>
      <webElementGuid>cfa17da4-cebb-4dea-a5fc-2bd653820b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal--body-179&quot;)/div[@class=&quot;css-178yklu&quot;]/div[@class=&quot;css-19rpcnq&quot;]</value>
      <webElementGuid>97c0c507-de20-465f-bc2f-5582c37856a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-179']/div/div[4]</value>
      <webElementGuid>3c48b92a-8b3a-4905-960a-3fecbad4bc42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor ini sudah terdaftar'])[1]/following::div[3]</value>
      <webElementGuid>3349c63f-7555-42c9-88af-a5358e158c64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konfirmasi Kepemilikan Akun'])[1]/preceding::div[1]</value>
      <webElementGuid>a37b3caa-e299-49c2-9670-a4b757ae6cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='atau'])[1]/preceding::div[2]</value>
      <webElementGuid>b0e1e039-57e1-48aa-8a57-70b57aeea6e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Email tidak valid']/parent::*</value>
      <webElementGuid>1a249206-d34a-4a01-ac4e-6c590916b1ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div[4]</value>
      <webElementGuid>77f9181d-03ca-451f-8a1d-a0e964637210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Email tidak valid' or . = 'Email tidak valid')]</value>
      <webElementGuid>43990777-6663-48da-a2a7-821fa6f3588d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
