<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor ini sudah terdaftar_buyerIdentity</name>
   <tag></tag>
   <elementGuidId>ccbb8b9f-43b5-4631-8385-0dd4c4983e6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buyerIdentity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='buyerIdentity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>85b713eb-952a-4798-9222-f82a4c1c266b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>buyerIdentity</value>
      <webElementGuid>d8a8928e-6af0-4d6a-9413-99a0e8e18a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buyerIdentity</value>
      <webElementGuid>79d95580-fa90-4278-a013-30b703a2cf42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>d04a28c3-2f33-415b-9ad4-a3bdfe4a5c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan email terdaftar</value>
      <webElementGuid>e49f5e8d-b626-4748-bbc7-cb1aff6fd6d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-1wjiylp focus-visible</value>
      <webElementGuid>5a81eb6a-501c-4bd8-8136-2893ab3660a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buyerIdentity&quot;)</value>
      <webElementGuid>992bfaf4-200f-4c69-ba96-54f9d4832b03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='buyerIdentity']</value>
      <webElementGuid>bf101735-cf18-4544-afea-f97b948cb485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-179']/div/div[3]/div/input</value>
      <webElementGuid>8e9f1026-6859-436f-84a1-dda242dcb7f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div[3]/div/input</value>
      <webElementGuid>bde8520a-c3bd-483c-a082-bbcb02b4a8c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'buyerIdentity' and @id = 'buyerIdentity' and @type = 'email' and @placeholder = 'Masukkan email terdaftar']</value>
      <webElementGuid>3f7afc7e-c20f-4673-8b8f-c6018ef7abee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
