<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_atau masukkan_guestIdentity</name>
   <tag></tag>
   <elementGuidId>234697cd-b0e0-4f5b-945a-4ea1e508ef68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#guestIdentity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='guestIdentity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc86effe-dfdb-40f7-b9cc-31f4b09480f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>guestIdentity</value>
      <webElementGuid>9fa588d1-20c2-4161-8fb4-2039c39e076e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>guestIdentity</value>
      <webElementGuid>a5d9415a-3a89-4938-9ecc-b577e659f262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan nomor HP atau email</value>
      <webElementGuid>9e8a0077-5156-49eb-964e-97542dd850b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-mc7ouo focus-visible</value>
      <webElementGuid>2d89101f-ad84-4037-9c1c-05625cf2500a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;guestIdentity&quot;)</value>
      <webElementGuid>8d40fab4-3369-4057-a459-7d1bc21669b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='guestIdentity']</value>
      <webElementGuid>40d1f367-493b-488d-ae86-89c90d57f1c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div[2]/div/div[2]/div/div[3]/div/input</value>
      <webElementGuid>5fdb0815-e05a-43f2-8153-ff8c93366697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>022cdbb5-ef1a-4bbc-8685-9692c1de441c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'guestIdentity' and @id = 'guestIdentity' and @placeholder = 'Masukan nomor HP atau email']</value>
      <webElementGuid>7c0b988e-deeb-40be-a34a-470657922a36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
