<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kirim informasi pembelian ke orang tu_624cd8</name>
   <tag></tag>
   <elementGuidId>a62088c2-5d9c-40e9-bc65-0840f76b1e73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#parentIdentity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='parentIdentity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d370b7f6-8106-43f6-9fed-5ba7d99beaa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>parentIdentity</value>
      <webElementGuid>76f77e2c-6866-4cb6-a7a9-a51f59b71187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>parentIdentity</value>
      <webElementGuid>2658f678-4f21-4aa9-8ff1-77387bc0cd9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan nomor HP atau email</value>
      <webElementGuid>4ed8789f-49da-440e-9951-373e932f71b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-11nvjtu focus-visible</value>
      <webElementGuid>e0011a55-0285-4628-a07d-b906e5a3c68b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;parentIdentity&quot;)</value>
      <webElementGuid>b79ddc03-5666-4fdf-bbac-33145d2ea13c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='parentIdentity']</value>
      <webElementGuid>ab35651e-320d-42b1-b360-1bef76eb9684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div[2]/div/div[2]/div/div[6]/div/input</value>
      <webElementGuid>c1bc5b85-4dae-4116-9dcf-dc506c358d81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>0e240fd8-ec8d-42ad-a715-5bedf07e0355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'parentIdentity' and @id = 'parentIdentity' and @placeholder = 'Masukan nomor HP atau email']</value>
      <webElementGuid>c90ecc27-ff65-4669-9a56-ae87ef4d0fb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
