<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Beasiswa</name>
   <tag></tag>
   <elementGuidId>ffa3c4e4-4e8f-4f1d-9fd1-a9bf55c20a9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='rg-header']/div/div/div[2]/div[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a9719db5-c380-4448-90db-706c7079fe2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking-event-type</name>
      <type>Main</type>
      <value>landing_page__core__item_click</value>
      <webElementGuid>9b6cd3a3-4ee3-427d-8729-9054400b4f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking-context</name>
      <type>Main</type>
      <value>{&quot;product_name&quot;: &quot;ruangguru&quot;,&quot;cta_action&quot;: &quot;redirection&quot;,&quot;cta_action_detail&quot;: &quot;https://www.ruangguru.com/beasiswa&quot;,&quot;item_type&quot;: &quot;link&quot;,&quot;item_name&quot;: &quot;Beasiswa&quot;,&quot;item_category&quot;: &quot;cta&quot;,&quot;item_position&quot;: 5,&quot;item_serial&quot;: null,&quot;section_type&quot;: &quot;navbar&quot;,&quot;section_position&quot;: &quot;header&quot;,&quot;section_name&quot;: &quot;header_navbar&quot;}</value>
      <webElementGuid>f9c7554e-8130-4b82-a088-6928f01fb2ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.ruangguru.com/beasiswa</value>
      <webElementGuid>a0eb079e-6dc0-4b01-82a6-f34ba7a756d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Beasiswa</value>
      <webElementGuid>375ce860-8f3a-4ba3-8e47-fbd13d813daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rg-header&quot;)/div[@class=&quot;page-center hero-center&quot;]/div[@class=&quot;container-ruangguru-header&quot;]/div[@class=&quot;navigation__content&quot;]/div[@class=&quot;navig-link&quot;]/a[1]</value>
      <webElementGuid>4e52ab56-47fc-46e3-a48c-a42e8d9482e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='rg-header']/div/div/div[2]/div[6]/a</value>
      <webElementGuid>c7cd60b1-d5b8-46d2-912e-1405319e4ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Beasiswa')]</value>
      <webElementGuid>107b0ab0-6001-48e5-ad29-2e22c6ac0d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event'])[1]/following::a[1]</value>
      <webElementGuid>41a14f79-16fb-41cf-bfd3-2da65b00512a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promo'])[1]/following::a[2]</value>
      <webElementGuid>bc805a32-33fa-47b7-9f88-06774e67f57b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Testimoni'])[1]/preceding::a[1]</value>
      <webElementGuid>bdbeefdd-0e7c-423b-9baf-99cc4b7f07e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cara Perpanjang Paket'])[1]/preceding::a[3]</value>
      <webElementGuid>a7f47eb0-67f3-403f-8b2d-86307afbec32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Beasiswa']/parent::*</value>
      <webElementGuid>9f4a8a39-d88b-4494-9036-5ff656763f8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.ruangguru.com/beasiswa')]</value>
      <webElementGuid>55e74b27-7187-405b-b2cc-cef38dcc68a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a</value>
      <webElementGuid>06d93365-2eba-4d44-a699-d03acae6b493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.ruangguru.com/beasiswa' and (text() = 'Beasiswa' or . = 'Beasiswa')]</value>
      <webElementGuid>96200f5f-c968-4732-b804-8f56aeb72c50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
