<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>e9062938-b3cf-4c46-919a-921d8a073f58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jenjangModal']/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.close-jenjang</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d5e16652-7b26-4cbf-a08f-6c0e55bcd60c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking-event-type</name>
      <type>Main</type>
      <value>landing_page__core__item_click</value>
      <webElementGuid>34496905-1010-4962-8795-2d19be2007b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking-context</name>
      <type>Main</type>
      <value>{&quot;product_name&quot;: &quot;ruangguru&quot;,&quot;cta_action&quot;: &quot;close&quot;,&quot;cta_action_detail&quot;: &quot;close_popup_grade_selection&quot;,&quot;item_type&quot;: &quot;button&quot;,&quot;item_name&quot;: &quot;Close&quot;,&quot;item_category&quot;: &quot;cta&quot;,&quot;item_position&quot;: 0,&quot;item_serial&quot;: null,&quot;section_type&quot;: &quot;popup&quot;,&quot;section_position&quot;: &quot;body&quot;,&quot;section_name&quot;: &quot;popup_grade_selection&quot;}</value>
      <webElementGuid>1a80f0ce-5d4a-4894-b50a-01cb0d70c4c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close-jenjang</value>
      <webElementGuid>0b0fae45-aa3c-46b8-bb81-4f8cf938e231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>f8cc802e-a582-4620-bbbc-5962105428ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jenjangModal&quot;)/div[@class=&quot;modal-content-jenjang&quot;]/div[@class=&quot;modal-body-jenjang&quot;]/span[@class=&quot;close-jenjang&quot;]</value>
      <webElementGuid>7215884c-8591-4446-b304-74ceea92ce2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jenjangModal']/div/div/span</value>
      <webElementGuid>7e3ccfbd-e678-4bd1-9195-b2d03eb76e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- Kelas 12 IPA'])[1]/following::span[1]</value>
      <webElementGuid>69cb72ba-0c0c-4f62-87be-f2746fa0b291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SMA'])[2]/following::span[2]</value>
      <webElementGuid>f80b103f-a66a-41e2-9035-c7593f620c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAUD'])[2]/preceding::span[1]</value>
      <webElementGuid>a6b049ed-9f3e-42be-b2ab-2c4b00af9af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SD'])[2]/preceding::span[1]</value>
      <webElementGuid>8dd15713-dd74-4b66-8c99-b16dad0a6cc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/span</value>
      <webElementGuid>58abf5a2-effd-416a-bcf0-0f90f3a06ca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '×' or . = '×')]</value>
      <webElementGuid>48d1c3f9-95ba-4082-ab4a-ac9cdcfa9a75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
