<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Layanan</name>
   <tag></tag>
   <elementGuidId>6b91c562-c974-410e-b411-ca4ee3fe70bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#services > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='services']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f459b5c2-8aff-4ff0-9ac0-61fbd7db02c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>860c55e7-7beb-40fb-8340-433f923253a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Layanan</value>
      <webElementGuid>9df591f6-a89c-4411-9528-1cff1a465763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;services&quot;)/a[1]</value>
      <webElementGuid>6950bc9b-cf7b-4586-8399-9c3a5cfd63a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='services']/a</value>
      <webElementGuid>aae2945a-af0c-49a8-a1d1-840eb5d2dd24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Layanan')]</value>
      <webElementGuid>aff60cd9-d82b-4ac4-a1c1-5d6967e5d7cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Testimoni'])[1]/following::a[1]</value>
      <webElementGuid>8d68ccdb-58f0-456d-bae4-ba61ff52d549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beasiswa'])[1]/following::a[2]</value>
      <webElementGuid>5003db18-ab0c-4d42-8a14-2d913acf341f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cara Perpanjang Paket'])[1]/preceding::a[1]</value>
      <webElementGuid>505a3011-9f73-40e2-b9b1-aa3865ff53ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cara Bayar'])[1]/preceding::a[2]</value>
      <webElementGuid>3a1e3082-0b80-4dd9-a746-2c18625bc8d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Layanan']/parent::*</value>
      <webElementGuid>6658c38e-d672-43b8-a0ba-62199e625dcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>b254b59f-cb7a-443a-9378-7571883c9896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/a</value>
      <webElementGuid>c7f03891-94df-40fb-a469-2e949d4cae20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Layanan' or . = 'Layanan')]</value>
      <webElementGuid>34e5039f-00cd-4765-a086-7515014d1435</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
