<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_httpstinyurl.comrequestguru_close</name>
   <tag></tag>
   <elementGuidId>d30557e1-6e06-44b9-8833-397ad72f05b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>Ch</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>70aadb8c-348b-466b-af1f-945e55001d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>66c82af1-7aaf-4275-bc44-b1ad72c4e190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>31d518bc-c5f6-45a5-b1ff-1c4f9bfcfd81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>8935a52e-7f9e-4991-b51d-1682ef6ed124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>ee2263ad-109a-496b-ab9a-20b5f70e0f00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;staticBackdrop&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered modal-sm-c0&quot;]/div[@class=&quot;modal-content&quot;]/button[@class=&quot;close&quot;]</value>
      <webElementGuid>1e19531d-2e26-4785-98a9-61267ce35e02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[10]</value>
      <webElementGuid>5cbfcdc4-1ba1-42e6-b3c7-c541ad660914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='staticBackdrop']/div/div/button</value>
      <webElementGuid>063ce86f-9c67-42ac-b980-02e24fd0342a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://tinyurl.com/requestguru'])[1]/following::button[1]</value>
      <webElementGuid>ceeee4cf-0f80-442e-ad95-895d925ef8b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paling sering ditanyakan'])[1]/following::button[1]</value>
      <webElementGuid>09cb3c37-b3be-428d-a279-2e8c54065372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roboguru'])[1]/preceding::button[1]</value>
      <webElementGuid>3b1752f0-ec6f-4a01-b1ee-918dc09a9517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roboguru Plus'])[1]/preceding::button[1]</value>
      <webElementGuid>d8549f86-e8b9-45a1-8ecd-d02dee2d29eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/button</value>
      <webElementGuid>55de4257-8996-4155-83fa-554d96216f18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>d8bc76eb-18b2-4b6e-84c9-d6800ba80261</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
