<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_httpstinyurl.comrequestguru_img-fluid h_e9a8d8</name>
   <tag></tag>
   <elementGuidId>c2fb6ccb-a823-40a0-8d60-ec21e8fc257e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='staticBackdrop']/div/div/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-fluid.h-auto.img-c-close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9028bb90-1e40-4ed0-b163-2ac02093e3af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.ruangguru.com/hubfs/New%20Payment/LP%20TREASURE%20Letters%202022/close.svg</value>
      <webElementGuid>2d5db62f-22a3-4409-8da3-63f40089e2db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>f7fbf246-c714-4af7-930b-315473e70615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>8aacf6f9-865c-49c9-a434-c59be6a79a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid h-auto img-c-close</value>
      <webElementGuid>818480b2-cdd8-4635-b26d-08207e9c74e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>fb7b7503-98ee-40b1-86f8-ec8c33e2a1b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;staticBackdrop&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered modal-sm-c0&quot;]/div[@class=&quot;modal-content&quot;]/button[@class=&quot;close&quot;]/img[@class=&quot;img-fluid h-auto img-c-close&quot;]</value>
      <webElementGuid>075ef25a-d6c7-493b-80a9-bd0f7578305e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='staticBackdrop']/div/div/button/img</value>
      <webElementGuid>f412485c-70f7-45b5-acc3-02d9a0c1a5c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.ruangguru.com/hubfs/New%20Payment/LP%20TREASURE%20Letters%202022/close.svg')]</value>
      <webElementGuid>cc108ad7-5a1e-4591-964f-0536968061de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/button/img</value>
      <webElementGuid>b9a87749-2a01-4228-995f-cd8c79ac6292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.ruangguru.com/hubfs/New%20Payment/LP%20TREASURE%20Letters%202022/close.svg']</value>
      <webElementGuid>6437d435-0e34-4c91-b511-2f72f005a5c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
