<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Email yang dimasukkan harus valid</name>
   <tag></tag>
   <elementGuidId>af79530c-178b-419d-9c36-a8d81268bf57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-216-feedback</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='field-216-feedback']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>16ebd3cf-4f6d-4877-87ea-9778aa73e3b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>1f4eaed7-4dc6-43cf-be6c-476dd0c5b74b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-form__error-message css-2zf9tq</value>
      <webElementGuid>c422b611-d6ca-4822-986a-fba658d33763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-216-feedback</value>
      <webElementGuid>5ac5139b-e2f0-4611-8279-326b643f67fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email yang dimasukkan harus valid</value>
      <webElementGuid>c3e9906b-ffaf-4edf-aabf-d466216ac909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-216-feedback&quot;)</value>
      <webElementGuid>4ed16f66-062f-4752-b0d6-63f4b63b31e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='field-216-feedback']</value>
      <webElementGuid>f5e08b45-3c86-4408-a2f2-9f2bd1a540e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div[2]/div/div/div[3]/div[2]</value>
      <webElementGuid>646a3d94-412b-4066-b46d-ac9c4c3e3ec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email aktif'])[1]/following::div[2]</value>
      <webElementGuid>6280ef91-3ef9-4838-b9ee-21fa2cad30a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor handphone siswa'])[1]/following::div[5]</value>
      <webElementGuid>044bda37-976c-4f7c-82d7-da8bcc4991a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lanjut ke Draft Invoice'])[1]/preceding::div[1]</value>
      <webElementGuid>4243a95f-855f-4b56-8b00-72a4d6802fbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lanjut ke Draft Invoice'])[2]/preceding::div[2]</value>
      <webElementGuid>d5e558c2-96d3-439e-b9c0-d871e238e5c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Email yang dimasukkan harus valid']/parent::*</value>
      <webElementGuid>a08c32df-f59e-4a9f-8d77-ad4420a6da0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]</value>
      <webElementGuid>c5f8cc68-bd4c-4c69-b1cc-936db48124ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'field-216-feedback' and (text() = 'Email yang dimasukkan harus valid' or . = 'Email yang dimasukkan harus valid')]</value>
      <webElementGuid>45b002ea-dc52-4468-ae57-eee2174608a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
