<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Masuk ke akun Anda_css-erdq5c</name>
   <tag></tag>
   <elementGuidId>67d3c368-08a2-4812-b936-906403109aa8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.css-erdq5c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b3788b1d-eb26-484b-b191-83c56e8759d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-erdq5c</value>
      <webElementGuid>ced67de9-1b6c-4bf9-829d-25eb8de79acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>78ec617a-3a4a-4f87-907b-8f28a81c7432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-1q5axsn-AuthScreen_container-gradient&quot;]/div[@class=&quot;css-11c80v9-innerContainer&quot;]/div[@class=&quot;css-xkirvf-rightContent&quot;]/div[@class=&quot;css-1glvlr7-card&quot;]/div[@class=&quot;css-uu6wvl&quot;]/div[@class=&quot;fade transition-wrapper&quot;]/div[@class=&quot;css-1ruigy0&quot;]/div[@class=&quot;css-y40tfu&quot;]/form[@class=&quot;css-2imjyh&quot;]/div[@class=&quot;css-40e6r&quot;]/div[@class=&quot;css-1d9sve6&quot;]/input[@class=&quot;css-erdq5c&quot;]</value>
      <webElementGuid>d09d08c3-a62e-4dbd-a3a0-5fd5c40e8d2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>53aba232-9964-40af-a91e-3509ff17b23a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div/div/form/div/div/input</value>
      <webElementGuid>432af2e0-09bf-4ecd-83a3-f5f0717c740b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4f30879d-7173-4a60-aff8-ae8a8cf766b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>16c0e1d0-2098-4230-b0b3-c31c27103c3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
