<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Komponen Sistem Pernapasan Manusia</name>
   <tag></tag>
   <elementGuidId>06757a5c-9eba-470a-9c56-bbbde03d935f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/section/article/div/div/div[2]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.chakra-text.css-17cqkbj</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d329e1dd-f2b7-4855-a632-6e0f5329d694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-text css-17cqkbj</value>
      <webElementGuid>28cc3ca3-0ce1-4151-8487-580924c0d5f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ruangbelajar/v/komponen-sistem-pernapasan-manusia-subtopi-yul7vb95-hr-sma-kelas-12-kurikulum-merdeka</value>
      <webElementGuid>84125751-e55a-4807-85ae-03a04a5d6410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Komponen Sistem Pernapasan Manusia</value>
      <webElementGuid>756d51e9-9040-4d0a-8ddc-0b54c845a42f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;css-1f5whys&quot;]/div[@class=&quot;css-1ubbntx&quot;]/section[@class=&quot;chakra-stack css-evkuat&quot;]/article[@class=&quot;chakra-stack css-1egbou&quot;]/div[@class=&quot;css-ad2za6&quot;]/div[@class=&quot;css-lcuzc0&quot;]/div[@class=&quot;css-11x96np&quot;]/div[@class=&quot;css-1a52s2z&quot;]/a[@class=&quot;chakra-text css-17cqkbj&quot;]</value>
      <webElementGuid>cdd5581d-7a8f-4a43-8737-d7f9b49935f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/section/article/div/div/div[2]/div/a</value>
      <webElementGuid>673af222-20a7-45c3-8cd8-9a06a0b599a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Komponen Sistem Pernapasan Manusia')]</value>
      <webElementGuid>863d48cc-bf0b-45ce-941d-cc35aa1e6a11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sistem Pernapasan pada Hewan'])[1]/following::a[41]</value>
      <webElementGuid>6be7cceb-a0f1-4927-b9e2-bc79900a8add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gangguan pada Sistem Pernapasan'])[1]/following::a[43]</value>
      <webElementGuid>e2d1b770-9eb0-4fff-8083-446d6b6c1131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mekanisme Pernapasan Manusia'])[2]/preceding::a[1]</value>
      <webElementGuid>3a5e4091-5013-4424-a85e-043783622eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kapasitas Paru-paru dan Kontrol Pernapasan'])[2]/preceding::a[2]</value>
      <webElementGuid>dc52c084-dcbf-472c-9ebe-593461b2501f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/ruangbelajar/v/komponen-sistem-pernapasan-manusia-subtopi-yul7vb95-hr-sma-kelas-12-kurikulum-merdeka')])[2]</value>
      <webElementGuid>42db01c1-03f3-4d3b-8dc4-c3f191a33659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/div/div[2]/div/a</value>
      <webElementGuid>f5b87058-3018-4e51-934e-be073ac5bf25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ruangbelajar/v/komponen-sistem-pernapasan-manusia-subtopi-yul7vb95-hr-sma-kelas-12-kurikulum-merdeka' and (text() = 'Komponen Sistem Pernapasan Manusia' or . = 'Komponen Sistem Pernapasan Manusia')]</value>
      <webElementGuid>d12fdafe-bd29-4388-81a8-82d2ba1d95f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
