<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lewati</name>
   <tag></tag>
   <elementGuidId>76ef3551-f48d-4a1e-ac48-f551e07542a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.chakra-button.css-1exqw46</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>81b42dc3-1623-46eb-a8aa-5370068cb35f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aff13b46-cd90-4700-95ec-3bcfdb93bb0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button css-1exqw46</value>
      <webElementGuid>11f3d9b4-4473-4490-9d83-9d18c8dc2d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lewati</value>
      <webElementGuid>7311cc03-332c-441b-a87e-66d2b458d64c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coach-mark-tooltip-container&quot;)/div[@class=&quot;css-67834j&quot;]/div[@class=&quot;chakra-stack css-gqp2dt&quot;]/div[@class=&quot;chakra-stack css-1oeb4ru&quot;]/div[@class=&quot;chakra-stack css-84zodg&quot;]/button[@class=&quot;chakra-button css-1exqw46&quot;]</value>
      <webElementGuid>c8cfa436-0665-497d-af4a-7c563df28e2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>ce55a622-35dc-4707-93a1-b3b6a7b15488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='coach-mark-tooltip-container']/div/div/div/div/button</value>
      <webElementGuid>c920a3df-8af3-498f-9530-450338c5bd30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sumber Energi ⚡️'])[1]/following::button[2]</value>
      <webElementGuid>1f5691d5-5072-408b-9f8b-4bee480cd5c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fisika Inti ⚡️'])[1]/following::button[2]</value>
      <webElementGuid>88913828-57e1-42a0-b20a-4ed95b1c5fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berikutnya'])[1]/preceding::button[1]</value>
      <webElementGuid>e3ec3e92-8828-4912-809d-f229fd6a3dd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lewati']/parent::*</value>
      <webElementGuid>e69cf763-a3e2-46db-bc62-f7b15d30a1e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/div/div/button</value>
      <webElementGuid>3cf77fca-03c1-49b6-90dc-c6f6db718245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Lewati' or . = 'Lewati')]</value>
      <webElementGuid>f0a41fa9-020c-49f8-9264-03dfd29609eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
