<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Kelas 12</name>
   <tag></tag>
   <elementGuidId>4e33924d-9148-45b4-9f90-16b90f18c17d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='chip-SHP-IPFEVU2M']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#chip-SHP-IPFEVU2M</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d4fab591-0b75-4a28-94b9-c9f72f9badca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chip-SHP-IPFEVU2M</value>
      <webElementGuid>e12a4abf-696d-4c34-9ac0-b4ff626d029a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-i2pry9</value>
      <webElementGuid>95de4699-28f5-46cd-a0df-087e29a17ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kelas 12</value>
      <webElementGuid>0bb3f21d-b63f-450d-8d17-7dac0031980a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chip-SHP-IPFEVU2M&quot;)</value>
      <webElementGuid>2d308b8d-88fe-4606-8a7e-3bc5324c7a60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='chip-SHP-IPFEVU2M']</value>
      <webElementGuid>2c033d6d-ef69-4b24-83df-3c3d5683f9cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chip-group']/button[2]</value>
      <webElementGuid>b9045b2f-c58a-4378-bb37-7257890f578e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selengkapnya'])[1]/following::button[2]</value>
      <webElementGuid>7b6977b1-0ba7-4716-8e13-03096f1f64ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kamu tak perlu pelajari semua bab, cukup pelajari bab yang dipelajari di sekolah.'])[1]/following::button[2]</value>
      <webElementGuid>cb1446b1-3151-4a8c-88e1-0c1e1942deb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vektor ⚡️'])[1]/preceding::button[1]</value>
      <webElementGuid>34352142-f07d-4e1c-ab8e-35fb5a7debd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kinematika Gerak: Gerak Lurus ⚡️'])[1]/preceding::button[1]</value>
      <webElementGuid>d6bae250-9691-4093-a43e-1976fd471c1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>8ade449f-a051-465f-a80b-18b89df50b5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'chip-SHP-IPFEVU2M' and (text() = 'Kelas 12' or . = 'Kelas 12')]</value>
      <webElementGuid>df82aa52-d0b5-4725-9eef-d32b1cbce211</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
