<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Daftar                    Sekarang</name>
   <tag></tag>
   <elementGuidId>7bf066c4-a2fc-4bdc-8a3a-a823891c96ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.mitra-daftar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cara-ajak']/div/div[3]/a/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4d49c0bf-f502-40e1-84fc-136f652bf773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mitra-daftar</value>
      <webElementGuid>0e664cc1-760d-4529-aa6a-22aa80e9a560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar
                    Sekarang</value>
      <webElementGuid>b2edb00e-d173-44a5-82f3-b529cd3c8bf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cara-ajak&quot;)/div[@class=&quot;page-center&quot;]/div[@class=&quot;invite__button&quot;]/a[1]/button[@class=&quot;mitra-daftar&quot;]</value>
      <webElementGuid>1e1f3210-c91e-4d29-b4f2-2c001c750a88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cara-ajak']/div/div[3]/a/button</value>
      <webElementGuid>b6da213b-1412-4fd9-8d10-ee846218b58b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yang Seru di Ruangguru'])[1]/following::button[1]</value>
      <webElementGuid>a0c735cd-4827-4800-9dc7-028006bf11be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bagaimana cara ajak orang pakai Kode Sahabat?'])[1]/following::button[1]</value>
      <webElementGuid>e2a3cba0-b5b0-4983-a4df-66f1f6bfe6d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk apa saja yang dapat diskon Kode Sahabat?'])[1]/preceding::button[1]</value>
      <webElementGuid>91fc994a-10f3-44e7-8eaf-ffcddce5a0c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='download'])[1]/preceding::button[1]</value>
      <webElementGuid>3a5143c6-cefa-4454-96ec-3e65d713b5c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>31049abc-244e-4831-8f9c-809049710a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Daftar
                    Sekarang' or . = 'Daftar
                    Sekarang')]</value>
      <webElementGuid>67f55c4a-499e-43c5-9a06-17f89b1de01b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
