<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lanjutkan</name>
   <tag></tag>
   <elementGuidId>05ad668b-650c-4fad-845d-210f31f89cd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.chakra-button.css-7f1ak6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>43f3475f-cb62-409d-b857-eeb228cb7668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a11dc515-6162-4acd-aa11-40c483bb5cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button css-7f1ak6</value>
      <webElementGuid>d605553e-61a5-497a-a17f-98fecc6de036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lanjutkan</value>
      <webElementGuid>bbeab160-177d-4fcd-b83e-b5a226b6d053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1554bj2&quot;]/div[@class=&quot;css-12esye9&quot;]/div[@class=&quot;layout-wrapper css-1gual9u&quot;]/div[@class=&quot;chakra-stack layout-form-card css-pqoyt4&quot;]/div[@class=&quot;layout-content css-80gtio&quot;]/div[@class=&quot;chakra-stack css-egoftb&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;chakra-stack css-egoftb&quot;]/form[@class=&quot;chakra-stack css-egoftb&quot;]/div[@class=&quot;css-1ayfwcb&quot;]/button[@class=&quot;chakra-button css-7f1ak6&quot;]</value>
      <webElementGuid>09883a66-d671-4c6e-8a37-cb948eacf198</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>cb754be0-d3af-4aec-8bd5-7e00b71ec64b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[2]/div[2]/div/div/div/form/div[2]/button</value>
      <webElementGuid>87732118-ce7b-41c5-8e7a-81500b15e7e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Google'])[1]/preceding::button[1]</value>
      <webElementGuid>db506508-c7c5-4475-b2d4-5d78683d6ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facebook'])[1]/preceding::button[2]</value>
      <webElementGuid>c8cf3b13-8a30-423a-a769-b2acf0d5d233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lanjutkan']/parent::*</value>
      <webElementGuid>6e75fda1-cd0e-4e4b-b231-7adc0bf7055b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>42530e7d-9249-4486-bfb3-1e3622f7546d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Lanjutkan' or . = 'Lanjutkan')]</value>
      <webElementGuid>ae5b63c4-8021-493d-8a4d-d950544253e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
