<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Email yang dimasukkan tidak benar</name>
   <tag></tag>
   <elementGuidId>ab212064-10c1-48a2-a860-71828135cecd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-1-feedback</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='field-1-feedback']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>39e5e077-b1e4-4791-8788-d748cb7f6be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-1-feedback</value>
      <webElementGuid>ce783504-af4d-4d3e-961d-f0eb3cc08a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>bb8e4466-f058-4ce6-9581-114716c491be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-form__error-message css-uv56vk</value>
      <webElementGuid>3cd4b026-7890-4beb-a1f2-b9ea29f712fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email yang dimasukkan tidak benar</value>
      <webElementGuid>9513abc9-36cd-4ba9-8fd2-9dcdba361492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-1-feedback&quot;)</value>
      <webElementGuid>673dae81-2c41-4af7-922c-b0bc2ff01d04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='field-1-feedback']</value>
      <webElementGuid>27cf1386-ad60-41bb-b6bf-a183dcc6ea77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[2]/div[2]/div/div/div/form/div/div[2]</value>
      <webElementGuid>4fb3bc1b-04f4-4720-8e4d-c1f614309550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lanjutkan'])[1]/preceding::div[1]</value>
      <webElementGuid>1964a925-2542-4e70-b6f2-48526b8fd8c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Google'])[1]/preceding::div[3]</value>
      <webElementGuid>878fdf6c-926b-4127-8397-7d279ec410b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Email yang dimasukkan tidak benar']/parent::*</value>
      <webElementGuid>6138560a-04a6-4dd0-afb5-82016f1b2c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]</value>
      <webElementGuid>54cef7a4-90f4-44fb-998f-7ba6ae9e0ff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'field-1-feedback' and (text() = 'Email yang dimasukkan tidak benar' or . = 'Email yang dimasukkan tidak benar')]</value>
      <webElementGuid>e55831fd-e78f-4bcf-8cfc-5591f79269bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
