<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Masukkan nomor HP atau email</name>
   <tag></tag>
   <elementGuidId>4d355494-3b5f-4dd2-b611-568652691451</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-1-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='field-1-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>1fd6c1e5-ebb4-41d0-8343-fd4b526c89d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>emailOrPhone</value>
      <webElementGuid>8da8dca0-2458-460c-84aa-5581a7b42bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-1-label</value>
      <webElementGuid>c323837f-2e7c-4ca3-9ba8-e4535c5b95cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-form__label css-cb3rqk</value>
      <webElementGuid>459d5d95-b64b-44a3-bd2b-91060189d9b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masukkan nomor HP atau email*</value>
      <webElementGuid>42164e96-02c4-4bf2-b659-aa3df8463dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-1-label&quot;)</value>
      <webElementGuid>b5bf06e2-685e-4805-bb3e-b2646c8caf36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='field-1-label']</value>
      <webElementGuid>17424608-4de7-4182-bc31-406faef599fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[2]/div[2]/div/div/div/form/div/div/label</value>
      <webElementGuid>d0adf686-efc4-4984-8ab2-f6e823d00807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lanjutkan'])[1]/preceding::label[1]</value>
      <webElementGuid>3b488e05-10f3-4e5e-a7df-3314e65f398f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Google'])[1]/preceding::label[1]</value>
      <webElementGuid>dc39b4d0-7bf8-442a-93c3-3669109f3edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Masukkan nomor HP atau email']/parent::*</value>
      <webElementGuid>72f610c8-e7cf-452f-b7de-061e7fb27a20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>db21d64a-82eb-412e-8786-e653c6b86536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'field-1-label' and (text() = 'Masukkan nomor HP atau email*' or . = 'Masukkan nomor HP atau email*')]</value>
      <webElementGuid>db662908-548d-4191-82b3-ea6c9007326c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
