<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_COBA GRATISKonsep Kilat0</name>
   <tag></tag>
   <elementGuidId>d88d6431-a8be-479f-b272-d85d664e3937</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div/div[3]/div/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.chakra-stack.css-1c09opa</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7f320bcc-f2b3-439d-bb40-2ef797a21467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-stack css-1c09opa</value>
      <webElementGuid>b1a4ae07-5c89-4355-b4bc-ba8b78637bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ruangbelajar/sma-kelas-12-kurikulum-merdeka/fisika/listrik-arus-searah/konsep-kilat</value>
      <webElementGuid>d96c3efe-df29-4644-8a1a-facf364be301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>COBA GRATISKonsep Kilat0%</value>
      <webElementGuid>2d60058b-72d4-4b1e-85a8-9811791b247e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;css-1f5whys&quot;]/div[@class=&quot;css-5m9o76&quot;]/div[@class=&quot;chakra-container css-3slsst&quot;]/div[@class=&quot;chakra-stack css-x9lkpl&quot;]/div[@class=&quot;css-8atqhb&quot;]/div[@class=&quot;css-34zyy1&quot;]/div[@class=&quot;css-8atqhb&quot;]/div[@class=&quot;chakra-skeleton css-1qwjt25&quot;]/a[@class=&quot;chakra-stack css-1c09opa&quot;]</value>
      <webElementGuid>a47b67b1-b083-4560-885f-c42c622e81f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div[3]/div/div/div/div/a</value>
      <webElementGuid>c2961fec-fb7d-4aee-bb92-b6f295e7c9f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Listrik Arus Searah ⚡️'])[2]/following::a[1]</value>
      <webElementGuid>380b4327-32c4-4f25-82e9-b8e844b5ec8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Listrik Arus Searah ⚡️'])[1]/following::a[1]</value>
      <webElementGuid>f190dc04-20aa-4079-b618-7819ad192df3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hambatan Listrik'])[1]/preceding::a[1]</value>
      <webElementGuid>eeadbdeb-1223-47d1-84d8-ed87aa0af5c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ruangbelajar/sma-kelas-12-kurikulum-merdeka/fisika/listrik-arus-searah/konsep-kilat')]</value>
      <webElementGuid>8acab139-79f9-484f-9ed9-e72464ab9de3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/a</value>
      <webElementGuid>d3f1f7c3-41b2-4480-a23e-cab6aca84cb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ruangbelajar/sma-kelas-12-kurikulum-merdeka/fisika/listrik-arus-searah/konsep-kilat' and (text() = 'COBA GRATISKonsep Kilat0%' or . = 'COBA GRATISKonsep Kilat0%')]</value>
      <webElementGuid>d3fb16ad-53d7-471b-9cff-b2e84d18a3ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
