<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Kelas 12</name>
   <tag></tag>
   <elementGuidId>bc9b8e06-8747-40d3-b2bd-97db6bc5f31e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='chip-SHP-IPFEVU2M']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#chip-SHP-IPFEVU2M</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e3895e17-e0fb-43a1-bd68-74f5d868f9fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chip-SHP-IPFEVU2M</value>
      <webElementGuid>7cf9753d-9f78-4826-ab7c-5d41ff979300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-i2pry9</value>
      <webElementGuid>afd6f0e8-8407-4981-a49b-e9d2dca3fc8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kelas 12</value>
      <webElementGuid>ff711f48-296f-4901-8916-8f67c1e50c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chip-SHP-IPFEVU2M&quot;)</value>
      <webElementGuid>34cc4bb2-476f-4be6-a392-5f3eb078b597</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='chip-SHP-IPFEVU2M']</value>
      <webElementGuid>45499399-2743-481e-8184-d2f888dfced1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chip-group']/button[2]</value>
      <webElementGuid>201b3583-43e5-45c7-8c33-0de999363db9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selengkapnya'])[1]/following::button[2]</value>
      <webElementGuid>c96b5b78-3dfa-4520-a3c1-7539a7c058c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kamu tak perlu pelajari semua bab, cukup pelajari bab yang dipelajari di sekolah.'])[1]/following::button[2]</value>
      <webElementGuid>7733aba1-ead2-44b2-971a-77d909799ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sel⚡️'])[1]/preceding::button[1]</value>
      <webElementGuid>15853323-6ee6-4bc2-8edd-4bbc2b2d9fb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pergerakan Zat melalui Membran Sel ⚡️'])[1]/preceding::button[1]</value>
      <webElementGuid>a86ae9f1-2a30-4101-a07f-2c5d8bf39498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>cf4c1142-0e0e-4171-abfb-dd057ef11f16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'chip-SHP-IPFEVU2M' and (text() = 'Kelas 12' or . = 'Kelas 12')]</value>
      <webElementGuid>995f4573-b50f-4139-94aa-d37852e3c584</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
