<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lewati</name>
   <tag></tag>
   <elementGuidId>62e03d31-7f77-4516-af0c-00579b902304</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.chakra-button.css-1exqw46</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4812572a-fb8e-4b9e-90c1-cdb8f0e3dad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>757d7df5-34ee-47e4-b2d2-25032c9182d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button css-1exqw46</value>
      <webElementGuid>8bb7b2a3-f3e5-4b77-a88e-89e2e850b25e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lewati</value>
      <webElementGuid>4450c59d-d6bb-461a-a148-752f583f28f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coach-mark-tooltip-container&quot;)/div[@class=&quot;css-67834j&quot;]/div[@class=&quot;chakra-stack css-gqp2dt&quot;]/div[@class=&quot;chakra-stack css-1oeb4ru&quot;]/div[@class=&quot;chakra-stack css-84zodg&quot;]/button[@class=&quot;chakra-button css-1exqw46&quot;]</value>
      <webElementGuid>814cfc9b-2092-40af-9586-3645239f33ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>677788f7-4217-4deb-b724-eb27f3109462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='coach-mark-tooltip-container']/div/div/div/div/button</value>
      <webElementGuid>b1fa594a-747a-4e64-b9ba-102048a587c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bioteknologi⚡️'])[1]/following::button[2]</value>
      <webElementGuid>de6fef03-106c-432a-8b5b-8520f0b4b788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pertumbuhan dan Perkembangan Hewan⚡️'])[1]/following::button[2]</value>
      <webElementGuid>f7002997-21e6-4d67-9cb7-7dc7eba088a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berikutnya'])[1]/preceding::button[1]</value>
      <webElementGuid>fa297d74-6f90-473c-813e-7ce9d6ddb4a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lewati']/parent::*</value>
      <webElementGuid>f5194375-2dc0-4691-93ad-324b701e1d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/div/div/button</value>
      <webElementGuid>bb1e6082-a360-495c-be0d-b67eae3c3fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Lewati' or . = 'Lewati')]</value>
      <webElementGuid>24e3b58b-bdc2-4e46-8573-fde7a2a03ae4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
