<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lihat Detail</name>
   <tag></tag>
   <elementGuidId>7340e26a-95d0-4f9d-947b-55427e8330c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-cards']/div[3]/div[4]/div[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2437c484-8a1a-4bf2-811e-db6045c65ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://rea.ruangguru.com/?referralCookiesId=8d0a761e-2319-412d-994b-21671cf17135</value>
      <webElementGuid>ad95e037-4981-4453-b760-b744324e8814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lihat Detail</value>
      <webElementGuid>886312d2-9f6d-4ebb-ac13-3dfcbce7c23c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-cards&quot;)/div[@class=&quot;content-card&quot;]/div[@class=&quot;card-event show&quot;]/div[@class=&quot;card-button pt-0&quot;]/a[1]</value>
      <webElementGuid>d0419a89-1d52-4a1c-bc26-8861efbe77f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-cards']/div[3]/div[4]/div[3]/a</value>
      <webElementGuid>d5eff872-4c96-46fc-b0e8-843f4e5b1b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Lihat Detail')])[4]</value>
      <webElementGuid>3177846f-44a0-4bdd-ad92-1418b9f8563d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ruangguru Engineering Academy'])[2]/following::a[1]</value>
      <webElementGuid>1089a3ef-ff73-44c2-8a62-2a211a0bd117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ruangguru Engineering Academy'])[1]/following::a[1]</value>
      <webElementGuid>5dfa8a55-82f7-4089-afef-0b249abb8877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sahabat Ruangguru'])[1]/preceding::a[2]</value>
      <webElementGuid>5e4e42e2-56f6-4f5c-a11c-61c974973c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Detail'])[5]/preceding::a[3]</value>
      <webElementGuid>828dc766-7448-4d58-8e8a-5c0cbeed1963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://rea.ruangguru.com/?referralCookiesId=8d0a761e-2319-412d-994b-21671cf17135')])[3]</value>
      <webElementGuid>13c4fbce-a93b-47ee-a831-5f5f907b5d44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/a</value>
      <webElementGuid>3fbb7dee-ff24-4056-89f8-c7b016c1d84e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://rea.ruangguru.com/?referralCookiesId=8d0a761e-2319-412d-994b-21671cf17135' and (text() = 'Lihat Detail' or . = 'Lihat Detail')]</value>
      <webElementGuid>07a2ddd7-0a0d-4080-bbef-b2f7dea4f5d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
