<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Kelas 12 IPS</name>
   <tag></tag>
   <elementGuidId>76500495-d940-4a71-a167-2f6cf2fbd216</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@value='kelas-12-ips']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>91f21f31-ea88-47e5-96a4-75189a1723ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking-event-type</name>
      <type>Main</type>
      <value>landing_page__core__item_click</value>
      <webElementGuid>11aa35c8-be7b-496c-baa3-cc863af005de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking-context</name>
      <type>Main</type>
      <value>{&quot;product_name&quot;: &quot;ruangguru&quot;,&quot;cta_action&quot;: &quot;selection&quot;,&quot;cta_action_detail&quot;: &quot;grade_selection&quot;,&quot;item_type&quot;: &quot;button&quot;,&quot;item_name&quot;: &quot;Kelas 12 IPS&quot;,&quot;item_category&quot;: &quot;cta&quot;,&quot;item_position&quot;: 5,&quot;item_serial&quot;: null,&quot;section_type&quot;: &quot;popup&quot;,&quot;section_position&quot;: &quot;body&quot;,&quot;section_name&quot;: &quot;popup_grade_selection&quot;}</value>
      <webElementGuid>4fc2857c-eeef-41db-af5f-6f310ba449be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cfeb9e38-b6b0-40bc-844b-29890fa095fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-grade</value>
      <webElementGuid>6a888635-f571-4f3e-88c3-f8990413f8c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>kelas-12-ips</value>
      <webElementGuid>e4b0c3bc-2a58-4cc8-a588-ea2e050ad690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-jenjang</name>
      <type>Main</type>
      <value>sma</value>
      <webElementGuid>d5092009-3e90-40f5-ae09-e5be64080d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kelas 12 IPS</value>
      <webElementGuid>267f2b70-0917-4375-b6dc-72a8edbeb38b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jenjangModal&quot;)/div[@class=&quot;modal-content-jenjang&quot;]/div[@class=&quot;modal-body-jenjang&quot;]/div[@class=&quot;modal-jenjang-kelas-wrapper&quot;]/div[@class=&quot;modal-jenjang-button-wrapper&quot;]/button[@class=&quot;btn-grade&quot;]</value>
      <webElementGuid>5e65692f-be72-489b-99d7-50c5a1c140c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@value='kelas-12-ips']</value>
      <webElementGuid>85964170-f9de-4272-b682-6041318aeea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jenjangModal']/div/div/div[2]/div/button[15]</value>
      <webElementGuid>a79127c2-b634-4674-8332-346dc8f11351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelas 12 IPA'])[1]/following::button[1]</value>
      <webElementGuid>e8245f40-5181-4924-970a-4589419c23f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelas 11 IPS'])[1]/following::button[2]</value>
      <webElementGuid>5808acc3-4b52-4f42-a21f-31eee320bff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ruangbelajar'])[2]/preceding::button[1]</value>
      <webElementGuid>4c094cc4-ee87-4f29-b3e4-ffa61e6bf436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kelas 12 IPS']/parent::*</value>
      <webElementGuid>5ba479d4-fc7a-4bf7-a2af-e6568a4c570a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[15]</value>
      <webElementGuid>3fe3b575-f45b-4bc3-987b-17bf11b5aa0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Kelas 12 IPS' or . = 'Kelas 12 IPS')]</value>
      <webElementGuid>ce1c79e2-e379-42fd-8ca6-28fc8ac3b992</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
