<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>6cd4334c-0e4d-47df-bdb4-fec301ec9f6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.close-jenjang</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jenjangModal']/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>746db74e-7db3-4c12-b9d5-fa9e26368b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking-event-type</name>
      <type>Main</type>
      <value>landing_page__core__item_click</value>
      <webElementGuid>e8118109-c43b-46d5-8dcd-cacf9bd4f89b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking-context</name>
      <type>Main</type>
      <value>{&quot;product_name&quot;: &quot;ruangguru&quot;,&quot;cta_action&quot;: &quot;close&quot;,&quot;cta_action_detail&quot;: &quot;close_popup_grade_selection&quot;,&quot;item_type&quot;: &quot;button&quot;,&quot;item_name&quot;: &quot;Close&quot;,&quot;item_category&quot;: &quot;cta&quot;,&quot;item_position&quot;: 0,&quot;item_serial&quot;: null,&quot;section_type&quot;: &quot;popup&quot;,&quot;section_position&quot;: &quot;body&quot;,&quot;section_name&quot;: &quot;popup_grade_selection&quot;}</value>
      <webElementGuid>4da57056-a204-4a3a-800f-857db5a29efb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close-jenjang</value>
      <webElementGuid>740a06fd-33a9-4357-a9ad-ba33e8b15a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>2b49d152-f259-42de-ab3b-95083fdcaf8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jenjangModal&quot;)/div[@class=&quot;modal-content-jenjang&quot;]/div[@class=&quot;modal-body-jenjang&quot;]/span[@class=&quot;close-jenjang&quot;]</value>
      <webElementGuid>c2397789-7185-42f0-bc0a-f986590a5b11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jenjangModal']/div/div/span</value>
      <webElementGuid>7103ab82-56b5-4861-9a11-3780f2428732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- Kelas 12 IPA'])[1]/following::span[1]</value>
      <webElementGuid>8141bebf-dd68-4aaa-b6da-9a4e20b9cbb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SMA'])[2]/following::span[2]</value>
      <webElementGuid>33e70d49-3211-4a52-b3c1-55a5087e59c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAUD'])[2]/preceding::span[1]</value>
      <webElementGuid>a558d024-d428-4fc5-9fbc-5af2c39f8528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SD'])[2]/preceding::span[1]</value>
      <webElementGuid>b44fd97c-3859-4355-9a11-7b7e16f3e833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/span</value>
      <webElementGuid>5240e095-f74c-482a-b2e7-d04814cff685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '×' or . = '×')]</value>
      <webElementGuid>00c1e4c6-4475-4a1c-9ff0-6c0556893dcd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
