<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ruangkelas_chakra-checkbox__control cs_5c7b1d</name>
   <tag></tag>
   <elementGuidId>b428f0c8-5244-4962-8dd9-aaa20e3107c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.chakra-checkbox__control.css-xxkadm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div/div/div/form/div[3]/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e8aa9a68-35b4-4d3c-be9a-82dbe854ccf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-checkbox__control css-xxkadm</value>
      <webElementGuid>56310193-13ae-48b2-8d6e-fb70e1f19b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>061ba99c-5304-49cb-9a16-df596d0f957a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1sa7zbu&quot;]/div[@class=&quot;css-rctf37&quot;]/div[@class=&quot;css-2c7zu0&quot;]/div[@class=&quot;chakra-stack css-egoftb&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;chakra-stack css-egoftb&quot;]/form[@class=&quot;chakra-stack css-egoftb&quot;]/div[@class=&quot;chakra-stack css-1bfzwix&quot;]/label[@class=&quot;chakra-checkbox css-1lc114p&quot;]/span[@class=&quot;chakra-checkbox__control css-xxkadm&quot;]</value>
      <webElementGuid>623803d3-5e6c-44c8-af72-2dc78d265ab1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div/div/form/div[3]/label/span</value>
      <webElementGuid>407cd35b-b92e-4e13-b23e-ac93a5fddf35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>1f3f14ed-cee6-4806-a6c3-f45c6e830cf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
