<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>19122cff-eb9d-4f7a-a922-8b5fd3f0845e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.close-jenjang</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jenjangModal']/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7719a362-b91d-413a-bc96-e64979477e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking-event-type</name>
      <type>Main</type>
      <value>landing_page__core__item_click</value>
      <webElementGuid>742f612e-0d5b-4fab-922d-e3a2fb373cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking-context</name>
      <type>Main</type>
      <value>{&quot;product_name&quot;: &quot;ruangguru&quot;,&quot;cta_action&quot;: &quot;close&quot;,&quot;cta_action_detail&quot;: &quot;close_popup_grade_selection&quot;,&quot;item_type&quot;: &quot;button&quot;,&quot;item_name&quot;: &quot;Close&quot;,&quot;item_category&quot;: &quot;cta&quot;,&quot;item_position&quot;: 0,&quot;item_serial&quot;: null,&quot;section_type&quot;: &quot;popup&quot;,&quot;section_position&quot;: &quot;body&quot;,&quot;section_name&quot;: &quot;popup_grade_selection&quot;}</value>
      <webElementGuid>06f12aa6-b270-45c4-bd19-a2cd389ad8dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close-jenjang</value>
      <webElementGuid>267bc40f-fba4-4bdb-83af-354330a1fa0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>ec0add4b-3905-4ee3-8adf-3e44aac442cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jenjangModal&quot;)/div[@class=&quot;modal-content-jenjang&quot;]/div[@class=&quot;modal-body-jenjang&quot;]/span[@class=&quot;close-jenjang&quot;]</value>
      <webElementGuid>1605af53-e368-4c7e-a32b-7eb7cc9b6111</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jenjangModal']/div/div/span</value>
      <webElementGuid>5ea506b2-10ee-4889-a6fa-71613ae84002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- Kelas 12 IPA'])[1]/following::span[1]</value>
      <webElementGuid>76b91c8f-45d8-4f1c-b078-7c192402ad22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SMA'])[2]/following::span[2]</value>
      <webElementGuid>d0b71f6f-a0ab-4b53-b2ed-d64ada2fecab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAUD'])[2]/preceding::span[1]</value>
      <webElementGuid>f8404549-1720-4eb2-be12-bdc323785f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SD'])[2]/preceding::span[1]</value>
      <webElementGuid>01f45656-4a94-444d-b29a-a45ed2b692a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/span</value>
      <webElementGuid>c7e6f574-9f3e-4ee9-89f6-8ea8219ba38f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '×' or . = '×')]</value>
      <webElementGuid>17848e28-f028-4bf4-a9c0-76ae84b3fdfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
