<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Timeline</name>
   <tag></tag>
   <elementGuidId>b2bcead3-3319-4bae-9c37-d287bd5d6037</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-rq2rez > div.chakra-container.css-1vsk1kk > h1.chakra-heading.css-m5dzzl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[5]/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>fccfb383-f659-43f3-8bbe-17e4626339e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-heading css-m5dzzl</value>
      <webElementGuid>e2d32150-4bc7-4b77-adbd-bf412d94ca10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Timeline</value>
      <webElementGuid>98d20e07-d0c4-465c-8f6f-09123fd1a0ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-zf0iqh&quot;]/div[@class=&quot;css-1kfj6vr&quot;]/div[@class=&quot;css-rq2rez&quot;]/div[@class=&quot;chakra-container css-1vsk1kk&quot;]/h1[@class=&quot;chakra-heading css-m5dzzl&quot;]</value>
      <webElementGuid>437d0787-4a34-4618-8556-b286930dcc3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[5]/div/h1</value>
      <webElementGuid>3c1a5f7b-d20f-47ef-bd76-3bd284059f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Docker Container Security'])[2]/following::h1[1]</value>
      <webElementGuid>caf0baa0-5c41-42d8-8bda-21f054c057ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Linux Basic Security'])[2]/following::h1[1]</value>
      <webElementGuid>dbc0c84b-1837-4724-a5b2-031845b862c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Requirements'])[1]/preceding::h1[1]</value>
      <webElementGuid>9bd66fe4-326d-4f30-971b-1bdc21de370e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Have a solid understanding of Algorithm and Data Structure.'])[1]/preceding::h1[2]</value>
      <webElementGuid>4c330a74-3b18-4738-a4c4-ff415cbef031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Timeline']/parent::*</value>
      <webElementGuid>77d4441f-207c-41cc-a631-fe6057cef739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/h1</value>
      <webElementGuid>d8587bc4-be7b-44d6-b7b2-244bd1fb842a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Timeline' or . = 'Timeline')]</value>
      <webElementGuid>8bd03180-866d-4525-a24b-a10ad77f8b2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
