<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Beasiswa</name>
   <tag></tag>
   <elementGuidId>5cf5441c-c1e2-47be-afc0-ea9ab3d905e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='rg-header']/div/div/div[2]/div[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9f1086c7-a7a6-468b-9614-9d1f789459d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking-event-type</name>
      <type>Main</type>
      <value>landing_page__core__item_click</value>
      <webElementGuid>ad12b299-90bc-4621-9631-b10e64b7b751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking-context</name>
      <type>Main</type>
      <value>{&quot;product_name&quot;: &quot;ruangguru&quot;,&quot;cta_action&quot;: &quot;redirection&quot;,&quot;cta_action_detail&quot;: &quot;https://www.ruangguru.com/beasiswa&quot;,&quot;item_type&quot;: &quot;link&quot;,&quot;item_name&quot;: &quot;Beasiswa&quot;,&quot;item_category&quot;: &quot;cta&quot;,&quot;item_position&quot;: 5,&quot;item_serial&quot;: null,&quot;section_type&quot;: &quot;navbar&quot;,&quot;section_position&quot;: &quot;header&quot;,&quot;section_name&quot;: &quot;header_navbar&quot;}</value>
      <webElementGuid>29ddc8a3-93e4-42ba-a7d5-16f95762fed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.ruangguru.com/beasiswa</value>
      <webElementGuid>75f4c88a-04fd-4a81-82b5-dccc9a2a2c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Beasiswa</value>
      <webElementGuid>8b3ba4cd-42ae-4ce8-ad4f-37ae6a4760df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rg-header&quot;)/div[@class=&quot;page-center hero-center&quot;]/div[@class=&quot;container-ruangguru-header&quot;]/div[@class=&quot;navigation__content&quot;]/div[@class=&quot;navig-link&quot;]/a[1]</value>
      <webElementGuid>4d60c29d-0d05-456a-af2f-719d704ea09d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='rg-header']/div/div/div[2]/div[6]/a</value>
      <webElementGuid>1c1914d8-f08b-41c7-bfcc-999a86d3974b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Beasiswa')]</value>
      <webElementGuid>b514d0b0-0f46-4433-b0d9-6e660a66ac01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event'])[1]/following::a[1]</value>
      <webElementGuid>4b43774f-098c-43bf-a380-2ac36622805e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promo'])[1]/following::a[2]</value>
      <webElementGuid>90b67983-c57d-421c-a162-5a821915b9c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Testimoni'])[1]/preceding::a[1]</value>
      <webElementGuid>4a911877-a5bd-4adc-bb84-0900ff069f1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cara Perpanjang Paket'])[1]/preceding::a[3]</value>
      <webElementGuid>9325953e-bf35-404c-943b-4f34b5986052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Beasiswa']/parent::*</value>
      <webElementGuid>f1532fec-33bf-4c17-80f6-7847a5b27b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.ruangguru.com/beasiswa')]</value>
      <webElementGuid>001e8889-ab69-42b7-a5df-169f9769aa43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a</value>
      <webElementGuid>e4fc6a4c-c7c1-4c61-9fb2-1487592ee340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.ruangguru.com/beasiswa' and (text() = 'Beasiswa' or . = 'Beasiswa')]</value>
      <webElementGuid>adf52855-fc63-4d4e-a3ce-349a5d269be2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
